import {useState} from 'react';
import {useSimStore} from '../store/useSimStore.js';
import {useUIStore} from '../store/useUIStore.js';
import {useCameraStore} from '../store/useCameraStore.js';
import {CAMERA_MODES,CAMERA_DEFAULTS} from '../navigation/model.js';
import {setCameraMode,focusCamera,cameraPreset,CAMERA_PRESETS} from '../navigation/actions.js';
import {AU,fromJulianDate} from '../physics/units.js';
import {Select,NumberField,Toggle,Readouts,fmt} from './Fields.jsx';
import {Field} from './styles.js';
export function speedLabel(value){return value>=AU*.001?fmt(value/AU,4)+' AU/s':value>=1000?fmt(value/1000,2)+' km/s':fmt(value,2)+' m/s';}
export default function CameraPanel({run}){
 const sim=useSimStore(),s=sim.scenario,store=useCameraStore(),v=s.view,n={...CAMERA_DEFAULTS,...v.navigation},[name,setName]=useState(''),[observer,setObserver]=useState('earth'),[target,setTarget]=useState('jupiter');
 const change=(key,value)=>run(()=>sim.configureView({navigation:{...n,[key]:value}})),bodies=s.bodies.filter(b=>b.visible&&!b.disrupted),choices=bodies.map(b=>[b.id,b.name]);
 const bookmarks=[...store.bookmarks,...v.savedCameras.filter(p=>p.positionSI&&!store.bookmarks.some(x=>x.id===p.id))];
 const persistBookmarks=()=>sim.configureView({savedCameras:useCameraStore.getState().bookmarks.slice(0,100)});
 return <div className="stack"><h2>Camera navigation</h2><Select label="Primary controller" value={store.live?.pose.mode??v.cameraMode} options={CAMERA_MODES.map(x=>[x,x.replace('-',' ').toUpperCase()])} commit={x=>setCameraMode(x)}/>
 <Select label="Camera target · independent of selection" value={v.cameraTarget??store.live?.pose.targetId??v.selected} options={choices} commit={id=>{sim.configureView({cameraTarget:id});useCameraStore.getState().request('mode',{mode:store.live?.pose.mode??v.cameraMode,targetId:id});}}/>
 <div className="grid"><button onClick={()=>setCameraMode('free')}>Free roam</button><button onClick={()=>focusCamera(v.selected)}>Focus selection · F</button><button onClick={()=>focusCamera(v.selected,'follow')}>Follow · Shift F</button><button onClick={()=>useCameraStore.getState().request('barycenter',{ids:[v.selected,s.bodies.find(b=>b.id===v.selected)?.parentId].filter(Boolean)})}>Orbit pair barycenter</button></div>
 <small>WASDQE moves along camera axes. Drag to look; middle drag pans. Wheel adjusts speed; Alt + wheel dollies. Shift boosts ×10, Ctrl slows ×0.001. Esc releases the current lock. C captures the pointer when supported.</small>
 <details open><summary>Movement and precision</summary><div className="stack"><Toggle label="Adaptive navigation speed" value={n.adaptiveSpeed} commit={x=>change('adaptiveSpeed',x)}/><Field>Base speed · {speedLabel(n.speed)}<input aria-label="Logarithmic camera speed" type="range" min="0" max={Math.log10(AU)} step=".05" value={Math.max(0,Math.log10(n.speed))} onChange={e=>sim.configureView({navigation:{...n,speed:10**+e.target.value,adaptiveSpeed:false}})}/></Field>
 <NumberField label="Manual speed" value={n.speed} unit="m/s" commit={x=>change('speed',Math.max(.01,Math.min(AU*10,x)))}/>
 <Select label="Quick movement speed" value={n.speed} options={[[1,'1 m/s'],[10,'10 m/s'],[100,'100 m/s'],[1000,'1 km/s'],[10000,'10 km/s'],[100000,'100 km/s'],[1e6,'1,000 km/s'],[AU*.001,'0.001 AU/s'],[AU*.01,'0.01 AU/s'],[AU*.1,'0.1 AU/s'],[AU,'1 AU/s'],[n.speed,'Custom']]} commit={x=>sim.configureView({navigation:{...n,speed:Number(x),adaptiveSpeed:false}})}/>
 <Select label="Q / E vertical axis" value={n.vertical} options={[['world','World up · J2000 ecliptic north'],['camera','Camera up']]} commit={x=>change('vertical',x)}/>
 <NumberField label="Mouse sensitivity · radians / pixel" value={n.sensitivity} commit={x=>change('sensitivity',Math.max(.0001,Math.min(.05,x)))}/><Toggle label="Invert mouse Y" value={n.invertY} commit={x=>change('invertY',x)}/><Toggle label="Unrestricted pitch" value={n.unrestricted} commit={x=>change('unrestricted',x)}/><Toggle label="Click for optional pointer lock" value={n.pointerLock} commit={x=>change('pointerLock',x)}/>
 <div className="grid">{[['translationDamping','Translation'],['rotationDamping','Rotation'],['zoomDamping','Zoom'],['followDamping','Follow']].map(([k,label])=><NumberField key={k} label={label+' damping · s⁻¹'} value={n[k]} commit={x=>change(k,Math.max(0,Math.min(100,x)))}/>)}</div></div></details>
 <details><summary>Frame, chase and clipping</summary><div className="stack"><Select label="Visualization reference frame" value={n.reference} options={[['inertial','Inertial J2000'],'sun','planet','moon','spacecraft','velocity']} commit={x=>{const selected=s.bodies.find(b=>b.id===v.selected),parent=s.bodies.find(b=>b.id===selected?.parentId),reference=x==='sun'?s.bodies.find(b=>b.type==='star'):x==='planet'?(selected?.type==='planet'?selected:parent):x==='moon'?s.bodies.find(b=>b.type==='moon'):x==='spacecraft'?s.bodies.find(b=>b.rocket||b.spacecraft):x==='velocity'?selected:null;sim.configureView({navigation:{...n,reference:x,referenceId:reference?.id??null}});}}/><Select label="Reference object" value={n.referenceId??v.selected} options={choices} commit={x=>change('referenceId',x)}/>
 <NumberField label="Field of view · degrees" value={n.fov} commit={x=>change('fov',Math.max(.1,Math.min(120,x)))}/><Select label="Chase direction" value={n.chaseOrientation} options={['velocity','attitude']} commit={x=>change('chaseOrientation',x)}/><NumberField label="Chase distance · object radii" value={n.chaseDistance} commit={x=>change('chaseDistance',Math.max(2,x))}/><NumberField label="Chase height · object radii" value={n.chaseHeight} commit={x=>change('chaseHeight',Math.max(0,x))}/><Toggle label="Camera collision protection" value={n.collision} commit={x=>change('collision',x)}/><Toggle label="Allow interior camera" value={n.allowInterior} commit={x=>change('allowInterior',x)}/><NumberField label="Minimum surface clearance · m" value={n.clearance} commit={x=>change('clearance',Math.max(0,x))}/><small>Frames translate the camera with the chosen reference. Velocity-relative also rotates the view with its velocity direction. Gravity retains the inertial SI basis.</small></div></details>
 <details><summary>Surface and telescope</summary><div className="stack"><div className="grid"><NumberField label="Surface latitude · °" value={n.surfaceLatitude} commit={x=>change('surfaceLatitude',Math.max(-90,Math.min(90,x)))}/><NumberField label="Longitude · °" value={n.surfaceLongitude} commit={x=>change('surfaceLongitude',Math.max(-180,Math.min(180,x)))}/></div><NumberField label="Surface altitude · m" value={n.surfaceAltitude} commit={x=>change('surfaceAltitude',Math.max(1,x))}/><button onClick={()=>useCameraStore.getState().request('surface',{id:v.selected})}>Surface view of selection</button><Select label="Telescope observer" value={observer} options={choices} commit={setObserver}/><Select label="Telescope target" value={target} options={choices.filter(([id])=>id!==observer)} commit={setTarget}/><Select label="Telescope FOV" value={n.fov} options={[[.1,'0.1°'],[.5,'0.5°'],[1,'1°'],[5,'5°'],[10,'10°'],[n.fov,'Current']]} commit={x=>change('fov',Number(x))}/><button onClick={()=>useCameraStore.getState().request('telescope',{observer,target,fov:n.fov<=10?n.fov:1})}>Observe through telescope</button><small>Spherical surfaces and geometric target pointing. Telescope switches to actual radii; there is no atmospheric seeing or light-time retarded image.</small></div></details>
 <details><summary>Presets, history and bookmarks</summary><div className="stack"><div className="grid">{CAMERA_PRESETS.map(p=><button key={p} onClick={()=>cameraPreset(p)}>{p}</button>)}</div><div className="row"><button disabled={store.index<=0} onClick={()=>store.travel(-1)}>Back · Alt ←</button><button disabled={store.index>=store.history.length-1} onClick={()=>store.travel(1)}>Forward · Alt →</button></div><Field>Bookmark name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Earth overview"/></Field><button onClick={()=>run(()=>{store.storeBookmarks(bookmarks);store.save(name);persistBookmarks();setName('');})}>Save current camera</button>
 {bookmarks.map(p=><div className="bookmark-row" key={p.id}><input aria-label={'Rename '+p.name} value={p.name} onChange={e=>{store.storeBookmarks(bookmarks.map(x=>x.id===p.id?{...x,name:e.target.value.slice(0,80)}:x));persistBookmarks();}}/><button onClick={()=>store.request('restore',{pose:p})}>Load</button><button aria-label={'Delete '+p.name} onClick={()=>{store.remove(p.id);sim.configureView({savedCameras:v.savedCameras.filter(x=>x.id!==p.id)});}}>×</button></div>)}
 <button onClick={()=>run(()=>{const p=store.live?.pose;if(p)sim.configureView({keyframes:[...v.keyframes,p].slice(-32)});})}>Add cinematic keyframe</button><small>{v.keyframes.length} keyframes · eight seconds per segment. Bookmarks store position, orientation, mode, FOV and reference.</small></div></details>
 <details><summary>Minimal overlays and diagnostics</summary><div className="stack">{[['minimalSpeed','Camera speed in Clean View'],['minimalDate','UTC in Clean View'],['minimalTarget','Target in Clean View'],['showNavigation','Automatic travel indicator']].map(([k,label])=><Toggle key={k} label={label} value={n[k]} commit={x=>change(k,x)}/>)}<Toggle label="Camera debug · F4" value={store.debug} commit={()=>store.toggle('debug')}/><Toggle label="Performance HUD · F3" value={store.performance} commit={()=>store.toggle('performance')}/></div></details>
 </div>;
}
export function CameraHUD(){
 const sim=useSimStore(),s=sim.scenario,ui=useUIStore(),store=useCameraStore(),live=store.live,n={...CAMERA_DEFAULTS,...s.view.navigation};if(!live)return null;
 const mode=live.pose.mode,target=s.bodies.find(b=>b.id===live.pose.targetId);
 return <>{(!ui.hidden||n.minimalSpeed||n.minimalDate||n.minimalTarget)&&<div className="camera-minimal" aria-label="Navigation status">{n.minimalSpeed&&<span><small>CAM SPEED</small> {speedLabel(live.speed*live.modifier)} {live.modifier!==1&&<b>{live.modifier<1?'PRECISION':'BOOST'}</b>}</span>}{n.minimalDate&&<span>{fromJulianDate(s.jd).toISOString().slice(0,19)} UTC</span>}{n.minimalTarget&&<span>{mode.toUpperCase()} · {target?.name??'Independent'}</span>}
 {!ui.hidden&&<><select aria-label="Camera mode" value={mode} onChange={e=>setCameraMode(e.target.value)}>{CAMERA_MODES.map(m=><option key={m} value={m}>{m.toUpperCase()}</option>)}</select><button aria-label="Open camera settings" onClick={()=>{ui.workspace({right:true});sim.configureView({panel:'camera'});}}>Navigation</button></>}
 {store.notice&&!ui.hidden&&<span className="warning">! {store.notice}</span>}{live.precisionLimit>Math.max(.001,(target?.radius??1)*.01)&&<span className="warning">! SI coordinate precision ~{fmt(live.precisionLimit,3)} m</span>}{live.collision&&<span className="warning">! Camera surface clearance</span>}{n.showNavigation&&live.transition&&<span>Camera travel → {target?.name??'System'} · {Math.round(live.transition.progress*100)}%</span>}</div>}
 {!ui.hidden&&store.debug&&<div className="camera-debug"><strong>CAMERA · F4</strong><Readouts values={[['Mode',mode.toUpperCase()],['Reference',n.reference+' / '+(n.referenceId??'none')],['Position · SI',live.pose.positionSI.map(x=>fmt(x,3)).join(' / ')],['Direction',live.direction.map(x=>fmt(x,5)).join(' / ')],['Speed',speedLabel(live.speed)],['Target',target?.name??'none'],['Near / far · m',fmt(live.near)+' / '+fmt(live.far)],['Render origin · SI',live.origin.map(x=>fmt(x)).join(' / ')],['Unit · m',fmt(live.unit)],['Pointer',live.pointerLocked?'Locked':'Released']]}/></div>}
 {!ui.hidden&&store.performance&&<div className="performance-hud"><strong>PERFORMANCE · F3</strong><Readouts values={[['FPS / frame',fmt(sim.fps,1)+' / '+fmt(sim.frameMs,2)+' ms'],['Physics',fmt(sim.stats?.computeMs,2)+' ms'],['Render CPU',fmt(sim.renderMs,2)+' ms'],['Bodies / particles',s.bodies.length+' / '+s.bodies.filter(b=>b.massless||b.disrupted).length],['Trail points',sim.activeTrailPoints??0],['Worker',fmt(sim.stats?.stepsPerSecond,1)+' steps/s'],['Integrator',sim.stats?.integratorActive??s.settings.integrator],['Gravity',sim.stats?.gravity??s.settings.solver],['Memory',sim.transport]]}/><small>CPU submission timing; GPU completion time is unavailable.</small></div>}
 </>;
}
