import {useState,useEffect,useRef,lazy,Suspense} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {useSimStore} from '../store/useSimStore.js';
import {useUIStore} from '../store/useUIStore.js';
import {PRESETS} from '../physics/catalog.js';
import {fromJulianDate,julianDate,AU,DAY} from '../physics/units.js';
import {api,exportScenario,scenarioLibrary,localScenario} from '../persistence.js';
import {loadHorizons} from '../horizons.js';
import {captureScreenshot} from '../capture.js';
import {Header,Rail,InspectorPanel,Footer,Notice,Dialog,Field} from './styles.js';
import {NumberField,Select,Toggle,Readouts,fmt} from './Fields.jsx';
import {SelectionInspector,BodyNavigator,ViewportControls,ScenarioArt,focusBody} from './Workspace.jsx';
import Icon from './Icon.jsx';
import Settings from './Settings.jsx';
const MissionControl=lazy(()=>import('./MissionControl.jsx'));
function Radar({s}) {
 const center=s.bodies.find(x=>x.id==='sun')?.position??s.bodies.find(x=>x.id==='earth')?.position??[0,0,0];
 const extent=Math.max(1,...s.bodies.map(b=>Math.hypot(b.position[0]-center[0],b.position[1]-center[1])));
 return <svg viewBox="0 0 130 110" style={{width:'100%'}} role="img" aria-label="Inertial system overview">{[20,36,49].map(r=><circle key={r} cx="65" cy="55" r={r} fill="none" stroke="#2b3845" strokeWidth=".6"/>)}<path d="M10 55H120M65 5V105" stroke="#29333f" strokeWidth=".5"/>
 {s.bodies.filter(b=>!b.massless||b.id===s.view.selected).slice(0,512).map(b=><circle key={b.id} cx={65+(b.position[0]-center[0])/extent*48} cy={55-(b.position[1]-center[1])/extent*48} r={b.id===s.view.selected?2.6:1.4} fill={b.color}/>)}</svg>;
}
function Modal({title,close,children}) {
 const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current.querySelector('input,button')?.focus();
 const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select,a[href],textarea')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
 document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><Dialog role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="row spread" style={{marginBottom:16}}><h2>{title}</h2><button aria-label="Close dialog" onClick={close}>×</button></div>{children}</Dialog></div>;
}
export default function HUD() {
 const sim=useSimStore(),ui=useUIStore(),s=sim.scenario,v=s.view,b=s.bodies.find(x=>x.id===v.selected),stats=sim.stats;
 const [notice,setNotice]=useState(''),[dialog,setDialog]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[saved,setSaved]=useState([]),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[date,setDate]=useState(fromJulianDate(s.jd).toISOString().slice(0,10)),[targets,setTargets]=useState(''),[playback,setPlayback]=useState(false),[tour,setTour]=useState(()=>localStorage.getItem('orrery-tour')?null:0);
 const [brushCount,setBrushCount]=useState(100);const input=useRef();const reduced=useReducedMotion();
 const run=async action=>{try{await action();}catch(error){setNotice(error.message);}};
 const setting=(key,value)=>run(()=>sim.edit(s=>s.settings[key]=value));
 const panel=name=>sim.configureView({panel:v.panel===name?null:name});
 useEffect(()=>{document.querySelector('[data-panel-scroll]')?.scrollTo(0,0);},[v.panel,v.selected]);
 const close=()=>{setDialog(null);setQuery('');};
 useEffect(()=>{document.documentElement.style.setProperty('--text-scale',v.textScale);document.body.classList.toggle('high-contrast',v.highContrast);document.body.classList.toggle('reduce-motion',v.reducedMotion);},[v.textScale,v.highContrast,v.reducedMotion]);
 useEffect(()=>{const key=e=>{
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setDialog('command');return;}
 if(e.target.closest('input,textarea,select,[contenteditable=true]'))return;
 if(e.target.closest('button,summary,[role=dialog]'))return;
 if(e.code==='Space'){e.preventDefault();useSimStore.getState().togglePause();}
 if(e.key==='?')setDialog('help');
 if(e.key==='Escape'){close();useUIStore.getState().update({tool:'select'});}
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const sim=useSimStore.getState();e.shiftKey?sim.redo():sim.undo();}
 if(e.key.toLowerCase()==='f')focusBody(useSimStore.getState().scenario.view.selected);
 };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(dialog==='catalog')scenarioLibrary().then(setSaved).catch(e=>setNotice(e.message));},[dialog]);
 const openPreset=id=>run(async()=>{sim.preset(id);await scenarioLibrary('save',useSimStore.getState().scenario,'recent:'+id);close();});
 const share=()=>run(async()=>{setBusy(true);try{const result=await api('/scenarios',{method:'POST',body:JSON.stringify(s)});localStorage.setItem('orrery-edit:'+result.id,result.editKey??result.edit_key);setLink(location.origin+'/s/'+result.id);setDialog('share');}finally{setBusy(false);}});
 const commands=[...PRESETS.map(p=>({label:'Load '+p.name,action:()=>openPreset(p.id)})),...s.bodies.filter(x=>!x.massless).slice(0,100).map(x=>({label:'Focus '+x.name,action:()=>sim.configureView({selected:x.id,scale:'planetary',camera:null})})),
 ...[['Pause / resume',()=>sim.togglePause()],['Convert to Sandbox',()=>sim.sandbox()],['Live Reality',()=>sim.reality()],['Double selected mass',()=>sim.action(v.selected,'mass',2)],['Double Jupiter mass',()=>sim.action('jupiter','mass',2)],['Spawn black hole here',()=>sim.spawn('blackHole',b?.position??[0,0,0],[0,0,0])],['Screenshot',captureScreenshot],['Undo',sim.undo],['Redo',sim.redo]].map(([label,action])=>({label,action}))];
 const matches=commands.filter(c=>c.label.toLowerCase().includes(query.toLowerCase())).slice(0,16);
 const runCommand=command=>run(()=>{command.action();close();});
 const warnings=stats?.warnings??[];const drift=stats?.conservationReliable&&Math.abs(stats.energyDrift)>0.01;
 return <>
 <Header><div className="brand"><div className="brand-mark"><Icon name="orbit" size={28}/></div><div><h1>ORRERY</h1><div className="brand-sub">SPACE EXPLORATION & DYNAMICS</div></div><span className="header-divider"/><span className="project-title">{s.name}</span></div>
 <div className="row"><div className="mode-switch" aria-label="Simulation mode"><button className={s.mode==='reality'?'active':''} onClick={()=>run(sim.reality)}>Reality</button><button className={s.mode==='sandbox'?'active':''} onClick={()=>run(sim.sandbox)}>Sandbox</button></div><span className="mode-label eyebrow">{s.provenance.source==='horizons'?'JPL Horizons':s.mode==='reality'?'Ephemeris':'Physics sandbox'}</span></div>
 <div className="row"><button className="command-button" aria-label="Open command palette" onClick={()=>setDialog('command')}><Icon name="search" size={15}/><span className="hide-mobile">Find anything</span><kbd>Ctrl K</kbd></button><button className="icon-button" aria-label="Help and shortcuts" onClick={()=>setDialog('help')}><Icon name="help" size={17}/></button></div></Header>
 <Rail aria-label="Workspace tools"><span className="rail-label">Explore</span>
 {[['inspector','inspect','Inspector'],['objects','objects','Objects'],['mission','mission','Mission control'],['tools','tools','Create objects'],['analysis','analysis','Prediction'],['events','events','Event log']].map(([name,icon,label])=><button key={name} aria-label={label} title={label} className={'toolbar-button '+(v.panel===name?'active':'')} onClick={()=>panel(name)}><Icon name={icon} size={20}/><span className="toolbar-label">{label}</span></button>)}
 <span className="rail-label">Library</span><button aria-label="Scenarios" className="toolbar-button" onClick={()=>setDialog('catalog')}><Icon name="catalog" size={20}/><span className="toolbar-label">Scenario library</span></button><button aria-label="Horizons" className="toolbar-button" onClick={()=>setDialog('ephemeris')}><Icon name="horizons" size={20}/><span className="toolbar-label">Epoch & Horizons</span></button>
 <div className="rail-bottom"><button aria-label="Undo edit" title="Undo edit" disabled={!sim.undoCount} onClick={sim.undo}><Icon name="undo" size={16}/></button><button aria-label="Redo edit" title="Redo edit" disabled={!sim.redoCount} onClick={sim.redo}><Icon name="redo" size={16}/></button><button aria-label="Export scenario" title="Export scenario" onClick={()=>run(()=>exportScenario(s))}><Icon name="download" size={16}/></button></div>
 <button aria-label="Simulation settings" className={'toolbar-button '+(v.panel==='settings'?'active':'')} onClick={()=>panel('settings')}><Icon name="settings" size={20}/><span className="toolbar-label">Simulation settings</span></button></Rail>
 <div className={v.panel?'':'workspace-no-panel'}><ViewportControls/></div><BodyNavigator/>
 {v.panel&&<InspectorPanel as={motion.section} initial={{opacity:0,x:reduced||v.reducedMotion?0:12}} animate={{opacity:1,x:0}} transition={{duration:.18}} aria-label={v.panel+' panel'} data-panel-scroll key={v.panel}>
 <div className="row spread"><span className="eyebrow">{({inspector:'Object details',settings:'Workspace settings',mission:'Flight operations',tools:'Creation tools',analysis:'Trajectory analysis',events:'Simulation log',objects:'Object directory'})[v.panel]}</span><button style={{minHeight:24,padding:'2px 7px'}} aria-label="Collapse panel" onClick={()=>sim.configureView({panel:null})}>×</button></div>
 {v.panel==='inspector'&&<SelectionInspector key={v.selected} run={run}/>}
 {v.panel==='settings'&&<Settings run={run}/>}
 {v.panel==='mission'&&<Suspense fallback={<small>Loading mission tools…</small>}><MissionControl run={run}/></Suspense>}
 {v.panel==='objects'&&<><h2>System objects</h2><Field>Filter<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or type"/></Field>
 {s.bodies.filter(b=>(b.name+' '+b.type).toLowerCase().includes(query.toLowerCase())).slice(0,200).map(b=><button className={v.selected===b.id?'active':''} key={b.id} onClick={()=>sim.configureView({selected:b.id,panel:'inspector'})}><span className="row spread"><span>{b.name}</span><small>{b.type}</small></span></button>)}<small>List limited to 200 matches. Particles remain selectable in the viewport.</small></>}
 {v.panel==='tools'&&<><h2>Create & modify</h2><small>{s.mode==='reality'?'Convert to Sandbox to alter physics.':'Edits apply at the next worker revision and can be undone.'}</small>
 <Select label="Spawn type" value={ui.spawnKind} options={['planet','star','asteroid','comet','moon','satellite','spacecraft','test particle','custom','blackHole','wormhole','neutronStar','whiteDwarf','pulsar']} commit={x=>ui.update({spawnKind:x})}/>
 <div className="grid"><button disabled={s.mode!=='sandbox'} className={ui.tool==='spawn'?'active':''} onClick={()=>ui.update({tool:ui.tool==='spawn'?'select':'spawn'})}>Place in viewport</button>
 <button disabled={!b||s.mode!=='sandbox'} className={ui.tool==='throw'?'active':''} onClick={()=>ui.update({tool:ui.tool==='throw'?'select':'throw'})}>Throw selected</button></div>
 <small>Click the ecliptic plane to place; drag to set velocity. Drag direction becomes the inertial velocity direction. Escape cancels. Keyboard alternative: spawn below, then edit vectors.</small>
 <button disabled={s.mode!=='sandbox'} onClick={()=>run(()=>sim.spawn(ui.spawnKind,[AU,0,0],[0,30000,0]))}>Spawn at 1 AU</button>
 <NumberField label="Brush particle count" value={brushCount} commit={v=>setBrushCount(Math.max(1,Math.min(10000,Math.floor(v))))}/>
 <div className="grid">{['ring','cloud','stream','field'].map(kind=><button key={kind} disabled={!b||s.mode!=='sandbox'} onClick={()=>run(()=>sim.brush(b.id,kind,brushCount))}>{kind==='field'?'Asteroid field':kind}</button>)}</div>
 <small>Brushes create non-sourcing particles around the selected primary. Body-specific actions are in the Inspector.</small></>}
 {v.panel==='analysis'&&<><h2>Trajectory analysis</h2><Toggle label="Predict selected trajectory" value={v.predictionEnabled} commit={x=>sim.configureView({predictionEnabled:x})}/>
 <NumberField label="Prediction duration" value={v.predictionDuration??DAY*30} unit="d" units={['s','d','yr']} commit={x=>sim.configureView({predictionDuration:Math.max(1,x)})}/>
 <NumberField label="Path resolution" value={v.predictionResolution??120} commit={x=>sim.configureView({predictionResolution:Math.max(8,Math.min(512,Math.floor(x)))})}/>
 <NumberField label="Preview selected mass multiplier" value={sim.previewMass??1} commit={x=>{useSimStore.setState({previewMass:Math.max(0,x)});sim.configureView({predictionEnabled:true});}}/>
 <div className="row"><button disabled={s.mode!=='sandbox'||!b} onClick={()=>run(()=>{sim.action(b.id,'mass',sim.previewMass??1);useSimStore.setState({previewMass:null});})}>Apply preview</button><button onClick={()=>useSimStore.setState({previewMass:null})}>Reset preview</button></div>
 <small>{sim.predicting?'Integrating a cloned state…':sim.prediction?'Reached '+fmt(sim.prediction.advanced/DAY)+' days'+(sim.prediction.complete?'':' · compute budget reached'): 'Prediction uses a separate worker with a bounded compute budget.'}</small>
 {sim.prediction?.events.map(e=><div className="event" key={e.id}>{e.message}</div>)}<small>Dashed paths include planned burns. This is a finite-horizon numerical prediction, not a long-term stability guarantee.</small></>}
 {v.panel==='events'&&<><h2>Events and diagnostics</h2><Readouts values={[['Energy · J',fmt(stats?.energy)],['Energy drift · %',fmt(stats?.energyDrift,8)],['Angular drift · %',fmt(stats?.angularDrift,8)],['Linear momentum',(stats?.momentum??[]).map(x=>fmt(x)).join(' / ')],['Center of mass · m',(stats?.center??[]).map(x=>fmt(x)).join(' / ')],['Effective step',fmt(stats?.lastDt)+' s'],['Accepted / rejected',(stats?.accepted??0)+' / '+(stats?.rejected??0)],['Scaled error estimate',fmt(stats?.errorEstimate,5)],['Collision events',stats?.collisionCount??0],['Event energy adjustment',fmt(stats?.eventEnergyDelta)+' J']]}/>
 <small>Drift accounts for collision energy jumps. Pins, thrust, and 1PN change which invariants are meaningful.</small>{warnings.map(w=><p className="warning" style={{fontSize:11}} key={w}>! {w}</p>)}
 {drift&&<button onClick={()=>setting('stepSeconds',Math.max(.01,s.settings.stepSeconds/2))}>Increase accuracy · halve maximum step</button>}
 <div className="stack">{[...s.events].reverse().map(e=><div className="event" key={e.id}><div className="eyebrow">{e.kind} · {fromJulianDate(e.jd).toISOString().slice(11,19)} UTC</div>{e.message}</div>)}{!s.events.length&&<small>No collision, tidal, or mission events.</small>}</div></>}
 </InspectorPanel>}

 <Footer><div className="clock"><div className="eyebrow">Simulation UTC</div><div className="mono" style={{fontSize:12,marginTop:4}}>{fromJulianDate(s.jd).toISOString().replace('T',' ').slice(0,19)}</div><small className="mono">JD {s.jd.toFixed(6)}</small></div>
 <div className="row time-controls"><button className="play-button" aria-label={sim.paused?'Play simulation':'Pause simulation'} onClick={sim.togglePause}><Icon name={sim.paused?'play':'pause'} size={17}/></button><button aria-label="Step simulation" title="One maximum physics frame" onClick={sim.step}><Icon name="step" size={17}/></button><button aria-label="Reverse time" title="Reverse time; dissipative events are not undone" className={s.settings.timeScale<0?'active':''} onClick={()=>setting('timeScale',-s.settings.timeScale)}><Icon name="reverse" size={17}/></button></div>
 <Field className="speed">Rate · {fmt(Math.abs(s.settings.timeScale),0)}×<input aria-label="Simulation speed" type="range" min="0" max="8" step=".1" value={Math.log10(Math.abs(s.settings.timeScale))} onChange={e=>setting('timeScale',Math.sign(s.settings.timeScale)*10**+e.target.value)}/></Field>
 <div className="time-presets">{[[1,"Real time"],[3600,"1 h / s"],[86400,"1 d / s"]].map(([value,label])=><button key={value} className={Math.abs(s.settings.timeScale)===value?'active':''} onClick={()=>setting('timeScale',Math.sign(s.settings.timeScale)*value)}>{label}</button>)}</div>
 <select className="scale-selector" aria-label="Viewing scale" style={{maxWidth:142}} value={v.scale} onChange={e=>sim.configureView({scale:e.target.value,camera:null})}>{[['system','Solar system'],['planetary','Planetary system'],['earth','Earth orbit'],['vehicle','Object close-up'],['true','True scale']].map(([k,x])=><option key={k} value={k}>{x}</option>)}</select>
 <div className="transport"><div><span className="status-dot"/> {s.bodies.length} objects <span className="text-separator">/</span> {fmt(sim.fps,0)} FPS</div><div className={drift?'warning':'muted'}>{stats?.limited?'Compute-limited · clock slowed':sim.paused?'Paused':'Running'} · {stats?.integratorActive??s.settings.integrator}</div></div></Footer>
 {(notice||sim.error)&&<Notice role="alert"><div className="row spread"><span>{notice||sim.error}</span><button onClick={()=>{setNotice('');useSimStore.setState({error:null});}}>Dismiss</button></div></Notice>}
 {dialog==='catalog'&&<Modal title="Scenario library" close={close}><div className="stack"><div className="row"><input aria-label="Search scenarios" placeholder="Search scenarios, tags…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Scenario category" value={category} onChange={e=>setCategory(e.target.value)} style={{maxWidth:140}}>{['all','astronomy','dynamics','extreme','mission','satellite','particles','sandbox','saved'].map(x=><option key={x}>{x}</option>)}</select></div>
 <details><summary>Save, import or share this workspace</summary><div className="stack"><div className="grid"><Field>Scenario name<input value={s.name} onChange={e=>run(()=>sim.edit(s=>s.name=e.target.value))}/></Field><Field>Tags<input value={s.tags.join(", ")} onChange={e=>run(()=>sim.edit(s=>s.tags=e.target.value.split(",").map(x=>x.trim()).filter(Boolean)))}/></Field></div><Field>Description<textarea value={s.description} onChange={e=>run(()=>sim.edit(s=>s.description=e.target.value))}/></Field>
 <div className="row wrap"><button onClick={()=>run(async()=>{await scenarioLibrary('save',s);setSaved(await scenarioLibrary());setNotice('Saved locally.');})}>Save current</button><button onClick={()=>run(()=>exportScenario(s))}>Export JSON</button><button onClick={()=>input.current.click()}>Import JSON</button><button disabled={busy} onClick={share}>Share snapshot</button></div>
 </div></details><div className="catalog-grid">{category!=='saved'&&PRESETS.filter(p=>(category==='all'||p.category===category)&&(p.name+' '+p.description+' '+p.tags.join(' ')).toLowerCase().includes(query.toLowerCase())).map(p=><button className="catalog-item" key={p.id} onClick={()=>openPreset(p.id)}><ScenarioArt preset={p}/><span className="catalog-copy"><span className="eyebrow">{p.category}</span><strong>{p.name}</strong><small>{p.description}</small></span></button>)}</div>
 {(category==='all'||category==='saved')&&saved.length>0&&<><h3>Saved and recently opened</h3>{saved.filter(x=>x.scenario.name.toLowerCase().includes(query.toLowerCase())).map(x=><button key={x.id} className="row spread" onClick={()=>run(()=>{sim.replace(x.scenario);close();})}><span>{x.scenario.name}</span><small>{x.updatedAt.slice(0,10)}</small></button>)}</>}
 <Field>Open shared scenario<input placeholder="Share ID or /s/… URL" value={link} onChange={e=>setLink(e.target.value)}/></Field><button onClick={()=>run(async()=>{const id=link.trim().split('/').at(-1);sim.replace(await api('/scenarios/'+encodeURIComponent(id)));close();})}>Open shared snapshot</button>
 </div></Modal>}
 {dialog==='share'&&<Modal title="Shared snapshot" close={close}><div className="stack"><a href={link}>{link}</a><small>This URL grants read access. The edit key is retained in this browser only.</small><button onClick={()=>run(()=>navigator.clipboard.writeText(link))}>Copy link</button></div></Modal>}
 {dialog==='ephemeris'&&<Modal title="Epoch and Horizons" close={close}><div className="stack"><Field>UTC epoch<input type="date" value={date} min="1800-01-01" max="2050-12-31" onChange={e=>setDate(e.target.value)}/></Field>
 <div className="row"><button onClick={()=>run(()=>{sim.jump(date);close();})}>JPL Table 1 at date</button><button onClick={()=>run(()=>{sim.reality();close();})}>Live now</button></div>
 <Toggle label="One-day Horizons vector playback (33 samples)" value={playback} commit={setPlayback}/><Field>Optional targets<select multiple aria-label="Additional Horizons targets" value={targets.split(',')} onChange={e=>setTargets([...e.target.selectedOptions].map(x=>x.value).join(','))}>{['pluto','ceres','voyager1','voyager2','jwst'].map(x=><option key={x}>{x}</option>)}</select></Field>
 <button disabled={busy} onClick={()=>run(async()=>{setBusy(true);try{const result=await loadHorizons(s,{jd:julianDate(date),days:playback?1:0,targets:targets.split(',').filter(Boolean),progress:(n,total)=>setNotice('Horizons '+n+' / '+total)});sim.replace(result);close();setNotice('Horizons vectors loaded.');}finally{setBusy(false);}})}>{busy?'Loading ephemerides…':'Load NASA/JPL vectors'}</button>
 <small>Requires the backend and NASA availability. All supported current bodies load at the same epoch. Playback uses Hermite interpolation; initialization switches to locally propagated Sandbox physics. Approximate moon phases are replaced by Horizons vectors.</small></div></Modal>}
 {dialog==='command'&&<Modal title="Commands" close={close}><div className="stack"><input aria-label="Command search" placeholder="Search actions or type jump to YYYY-MM-DD" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){const date=query.match(/jump to (\d{4}-\d{2}-\d{2})/i);date?run(()=>{sim.jump(date[1]);close();}):matches[0]&&runCommand(matches[0]);}}}/>
 {matches.map((c,i)=><button key={i} style={{textAlign:'left'}} onClick={()=>runCommand(c)}>{c.label}</button>)}</div></Modal>}
 {dialog==='help'&&<Modal title="Controls and model scope" close={close}><div className="stack"><Readouts values={[['Orbit','Drag / touch'],['Zoom','Wheel / pinch'],['Pan','Right drag / two fingers'],['Select','Click body or Objects list'],['Pause / play','Space'],['Focus local','F'],['Command palette','Ctrl / Cmd + K'],['Undo / redo','Ctrl / Cmd + Z / Shift + Z'],['Free camera','W A S D · Q E · Shift'],['Cancel placement','Escape']]}/>
 <p>Reality uses approximate JPL elements or loaded Horizons vectors. Sandbox evolves worker-owned SI state. Reverse stepping integrates gravity; it does not reverse fuel use, collisions, or teleportation.</p><small>Massive sources are limited to 512, total objects to 20,000. Visual radius exaggeration does not alter collision radii. Moon phases, procedural maps, radio power and rocket atmosphere are approximations.</small><button onClick={()=>{setTour(0);close();}}>Show quick tour</button></div></Modal>}
 {tour!==null&&<Notice role="status" style={{maxWidth:400}}><div className="stack"><span className="eyebrow">Quick start · {tour+1} / 6</span><h3>{['Explore the workspace','Select an object','Control simulation time','Change the physics','Create a system','Try a mission'][tour]}</h3><p>{['Drag to orbit, wheel to zoom, or use touch gestures. The scale selector moves between system and vehicle views.','Click a body or open Objects. The Inspector shows its physical properties and live orbital elements.','Use the bottom clock, pause, reverse, and speed slider. Compute limits slow the simulated clock rather than skipping physics.','Convert to Sandbox before editing. Units are selectable per field. Every supported edit has Undo.','God Tools lets you place and throw bodies or brush rings and particle fields.','Scenarios includes launch vehicles, satellites, and extreme-object laboratories. Mission control shows actual worker telemetry.'][tour]}</p><div className="row"><button onClick={()=>{localStorage.setItem('orrery-tour','done');setTour(null);}}>Dismiss tour</button><button onClick={()=>{if(tour===5){localStorage.setItem('orrery-tour','done');setTour(null);}else setTour(tour+1);}}>{tour===5?'Finish':'Next'}</button></div></div></Notice>}
 <input ref={input} type="file" accept=".json,application/json" className="sr-only" aria-label="Import scenario JSON" onChange={e=>{const file=e.target.files[0];if(file)run(async()=>{if(file.size>32*1024*1024)throw new Error('Scenario exceeds 32 MiB');sim.replace(JSON.parse(await file.text()));close();});e.target.value='';}}/>
 </>;
}
