import {useState,useRef} from 'react';
import {useSimStore} from '../store/useSimStore.js';
import {useUIStore} from '../store/useUIStore.js';
import {useCameraStore} from '../store/useCameraStore.js';
import {useReplayStore} from '../store/useReplayStore.js';
import {enterReplay,exitReplay,replayFrame} from '../useReplay.js';
import {observation,observingStar,sunlight,resonance,rendezvous,rendezvousBurn,orbitChange,lagrangePoints} from '../physics/observations.js';
import {derived,body} from '../physics/body.js';
import {derivedOrbit,primaryFor} from '../physics/orbital.js';
import {spacecraftAt} from '../physics/catalog.js';
import {deltaVBudget,applyFuelBurn} from '../physics/flight.js';
import {G,AU,DAY,norm,sub,julianDate,fromJulianDate} from '../physics/units.js';
import {uid} from '../store/actions.js';
import {download} from '../persistence.js';
import {Select,NumberField,Readouts,Toggle,fmt} from './Fields.jsx';
import {Field} from './styles.js';
export function ObservationTools({run}){
 const sim=useSimStore(),s=sim.scenario,[observerId,setObserver]=useState('earth'),[targetId,setTarget]=useState('jupiter'),[dateName,setDateName]=useState(''),[epoch,setEpoch]=useState(fromJulianDate(s.jd).toISOString().slice(0,10));
 const observer=s.bodies.find(b=>b.id===observerId),target=s.bodies.find(b=>b.id===targetId),options=s.bodies.filter(b=>!b.disrupted).map(b=>[b.id,b.name]),star=observer?observingStar(s,observer):null,m=observer&&target?observation(observer,target,star,s.settings.c):null,light=observer&&star?sunlight(observer,star,s.bodies):null;
 return <div className="stack"><h2>Observation</h2><Select label="Observer" value={observerId} options={options} commit={setObserver}/><Select label="Target" value={targetId} options={options.filter(([id])=>id!==observerId)} commit={setTarget}/>{m&&<><Readouts values={[['Distance',fmt(m.distance/1000)+' km'],['Relative speed',fmt(m.relativeSpeed/1000,3)+' km/s'],['Closing speed',fmt(m.closingSpeed,2)+' m/s'],['Apparent diameter',fmt(m.angularSize*180/Math.PI,6)+'°'],['One-way light time',fmt(m.lightTime,3)+' s ('+fmt(m.lightTime/60,2)+' min)'],['Phase angle',m.phaseAngle==null?'Self-luminous':fmt(m.phaseAngle*180/Math.PI,3)+'°'],['Illuminated hemisphere',m.illuminatedFraction==null?'—':fmt(m.illuminatedFraction*100,2)+'%'],['Observer sunlight',light.state.toUpperCase()],['Visible stellar disc',fmt(light.fraction*100,3)+'%']]}/><button onClick={()=>useCameraStore.getState().request('telescope',{observer:observerId,target:targetId,fov:1})}>Telescope · 1°</button><small>Instantaneous geometric observation from the observer centre. No retarded ephemeris, atmospheric refraction, or ground-site horizon model. Light delay uses the configured c.</small></>}
 <Toggle label="Planetary terminator guides" value={s.view.terminator??false} commit={x=>sim.configureView({terminator:x})}/><Toggle label="Idealized Lagrange points for selection" value={s.view.showLagrange??false} commit={x=>sim.configureView({showLagrange:x})}/><Toggle label="Hill sphere" value={s.view.showHill} commit={x=>sim.configureView({showHill:x})}/>
 <details><summary>Time bookmarks</summary><div className="stack"><Field>Bookmark name<input value={dateName} onChange={e=>setDateName(e.target.value)} placeholder="Mars launch epoch"/></Field><Field>UTC date<input type="date" min="1800-01-01" max="2050-12-31" value={epoch} onChange={e=>setEpoch(e.target.value)}/></Field><button onClick={()=>run(()=>sim.edit(d=>d.view.timeBookmarks=[...d.view.timeBookmarks,{name:dateName.trim().slice(0,80)||epoch,jd:julianDate(epoch)}].slice(-100)))}>Save date</button>
 {(s.view.timeBookmarks??[]).map((p,i)=><div className="row spread" key={i}><button disabled={s.mode!=='reality'} title={s.mode==='reality'?'Reinitialize approximate Reality at this epoch':'Sandbox requires recorded state, not a date bookmark'} onClick={()=>run(()=>sim.jump(fromJulianDate(p.jd)))}>{p.name}</button><small>{fromJulianDate(p.jd).toISOString().slice(0,10)}</small><button aria-label={'Delete '+p.name} onClick={()=>run(()=>sim.edit(d=>d.view.timeBookmarks=d.view.timeBookmarks.filter((_,j)=>j!==i)))}>×</button></div>)}<small>Date bookmarks reinitialize Reality. Sandbox time restoration is available only for captured replay snapshots.</small></div></details></div>;
}
export function PlanetComparison(){
 const sim=useSimStore(),s=sim.scenario,[ids,setIDs]=useState(['earth','mars']),available=s.bodies.filter(b=>!b.massless&&!b.disrupted),bodies=ids.map(id=>available.find(b=>b.id===id)).filter(Boolean),largest=Math.max(1,...bodies.map(b=>b.radius));
 const rows=bodies.map(b=>{const d=derived(b,s.settings),o=derivedOrbit(b,s.bodies,s.settings);return {b,d,o};});
 return <div className="stack"><h2>Compare worlds</h2><Field>Choose two or more objects<select multiple aria-label="Comparison objects" value={ids} onChange={e=>setIDs([...e.target.selectedOptions].map(x=>x.value).slice(0,8))}>{available.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><small>Ctrl / Cmd selects multiple. Comparison does not rearrange or edit the simulated bodies.</small>
 <svg viewBox={'0 0 290 '+Math.max(70,bodies.length*70)} className="size-comparison" role="img" aria-label="Bodies compared with the same physical radius scale">{bodies.map((b,i)=><g key={b.id}><circle cx="38" cy={i*70+32} r={b.radius/largest*28} fill={b.color}/><text x="78" y={i*70+28} fill="#d5dce3" fontSize="11">{b.name}</text><text x="78" y={i*70+44} fill="#8d9aaa" fontSize="10">{fmt(b.radius/1000)} km radius</text></g>)}</svg>
 <div className="comparison-table"><table><thead><tr><th>Metric</th>{bodies.map(b=><th key={b.id}>{b.name}</th>)}</tr></thead><tbody>{[['Radius · km',x=>fmt(x.b.radius/1000)],['Mass · kg',x=>fmt(x.b.mass)],['Density · kg/m³',x=>fmt(x.d.density)],['Gravity · m/s²',x=>fmt(x.d.surfaceGravity,3)],['Escape · km/s',x=>fmt(x.d.escapeVelocity/1000,3)],['Orbital speed · km/s',x=>fmt(norm(x.o.primary?sub(x.b.velocity,x.o.primary.velocity):x.b.velocity)/1000,3)],['Day · h',x=>fmt(Math.abs(x.b.spin.period)/3600,3)],['Period · d',x=>x.o.elements?.period?fmt(x.o.elements.period/DAY,3):'Unbound']].map(([label,value])=><tr key={label}><th>{label}</th>{rows.map(x=><td key={x.b.id}>{value(x)}</td>)}</tr>)}</tbody></table></div>{bodies.length===2&&(()=>{const r=resonance(bodies[0],bodies[1],s.bodies,s.settings);return r?<small>{r.label} · period ratio {fmt(r.ratio,6)}. {r.model}</small>:<small>No low-order period commensurability within 1% is established by this snapshot.</small>;})()}</div>;
}
export function RendezvousTools({run}){
 const sim=useSimStore(),s=sim.scenario,b=s.bodies.find(b=>b.id===s.view.selected),[targetId,setTarget]=useState(s.bodies.find(x=>x.spacecraft&&x.id!==b?.id)?.id??'earth'),[hold,setHold]=useState(100),[pe,setPe]=useState(200000),[ap,setAp]=useState(200000),target=s.bodies.find(x=>x.id===targetId),primary=b?primaryFor(b,s.bodies):null,[preview,setPreview]=useState(null);
 const plan=dv=>run(()=>{if(!b?.rocket&&!b?.spacecraft)throw new Error('Select a vehicle');setPreview({bodyId:b.id,epochJD:s.jd,dv});const clone=structuredClone(s);clone.maneuvers.push({id:'encounter-preview',bodyId:b.id,jd:s.jd,deltaV:norm(dv),direction:'vector',vector:dv,executed:false,fuelAware:!!b.rocket});useUIStore.getState().update({maneuverPreview:clone});sim.configureView({predictionEnabled:true,targetId});});
 const queue=()=>run(()=>sim.edit(d=>{if(preview.epochJD!==d.jd)throw new Error('Preview is stale; pause and calculate again');d.maneuvers.push({id:uid('encounter'),bodyId:b.id,jd:d.jd,deltaV:norm(preview.dv),direction:'vector',vector:preview.dv,executed:false,fuelAware:!!b.rocket});useUIStore.getState().update({maneuverPreview:null});setPreview(null);}));
 const r=b&&target?rendezvous(b,target):null,vehicle=!!(b?.rocket||b?.spacecraft),currentAltitude=primary&&b?norm(sub(b.position,primary.position))-primary.radius:null;
 return <div className="stack"><h2>Encounter operations</h2><small>Selected: {b?.name??'none'} · primary {primary?.name??'none'}</small><Select label="Rendezvous target" value={targetId} options={s.bodies.filter(x=>x.id!==b?.id&&!x.disrupted).map(x=>[x.id,x.name])} commit={id=>{setTarget(id);sim.configureView({targetId:id});}}/>
 {r&&<Readouts values={[['Relative distance',fmt(r.distance,3)+' m'],['Relative speed',fmt(r.speed,3)+' m/s'],['Closing speed',fmt(r.closingSpeed,3)+' m/s'],['Relative position',r.relativePosition.map(x=>fmt(x)).join(' / ')],['Relative velocity',r.relativeVelocity.map(x=>fmt(x,3)).join(' / ')],['Alignment',r.alignment==null?'No attitude data':fmt(r.alignment*180/Math.PI,2)+'°'],['Docking readiness',r.dockable?'Within geometric thresholds':'Not aligned / closing too fast / too far']]}/>}
 <NumberField label="Hold / approach distance · m" value={hold} commit={x=>setHold(Math.max(20,x))}/><div className="grid"><button disabled={!vehicle||!target} onClick={()=>plan(rendezvousBurn(b,target,'match',hold))}>Preview velocity match</button><button disabled={!vehicle||!target} onClick={()=>plan(rendezvousBurn(b,target,'approach',hold))}>Preview approach / hold</button></div><small>Approach targets at most 10 m/s closing speed and a 120 s proportional horizon. This is an impulsive guidance aid, not autonomous docking or rigid-body contact.</small>
 <details open><summary>Escape and capture</summary><div className="stack"><Readouts values={[['Current altitude',currentAltitude==null?'—':fmt(currentAltitude/1000,3)+' km']]}/><button disabled={!vehicle||!primary} onClick={()=>plan(orbitChange(b,primary,s.settings,{escape:true}))}>Preview escape burn</button>
 <div className="grid"><NumberField label="Target periapsis · km" value={pe} unit="km" commit={setPe}/><NumberField label="Target apoapsis · km" value={ap} unit="km" commit={setAp}/></div><button disabled={!vehicle||!primary} onClick={()=>plan(orbitChange(b,primary,s.settings,{periapsis:pe,apoapsis:ap}))}>Preview capture / orbit change</button><small>Current radius must be between the chosen apsides. Set an apsis to the current altitude for a purely tangential capture at that point.</small></div></details>
 {preview&&<><Readouts values={[['Planned Δv',fmt(norm(preview.dv),3)+' m/s'],['Remaining staged Δv',b?.rocket?fmt(deltaVBudget(b.rocket).total,1)+' m/s':'Ideal satellite impulse']]}/><button disabled={s.mode!=='sandbox'} onClick={queue}>Confirm maneuver</button><button onClick={()=>{setPreview(null);useUIStore.getState().update({maneuverPreview:null});}}>Discard preview</button><small>Pause before previewing to keep confirmation tied to the same physical state. Rocket confirmation will debit fuel when executed.</small></>}
 {sim.prediction?.closestApproach&&<Readouts values={[['Predicted closest approach',fmt(sim.prediction.closestApproach.distance/1000,3)+' km'],['Encounter in',fmt((sim.prediction.closestApproach.jd-s.jd)*DAY,1)+' s'],['Encounter relative speed',fmt(sim.prediction.closestApproach.relativeSpeed/1000,3)+' km/s'],['Integration segment',fmt(sim.prediction.closestApproach.resolutionSeconds,3)+' s']]}/>}<small>{sim.prediction&&!sim.prediction.complete?'Prediction reached its compute budget; closest approach covers only the reached horizon.':'Closest approach is measured over integrated segments, not inferred from a drawn ellipse.'}</small>
 <details><summary>Create a physical satellite orbit</summary><div className="stack">{[[200000,0,'200 km circular'],[400000,0,'400 km circular'],[1000000,0,'1,000 km circular'],[35786000,0,'GEO altitude · equatorial'],[600000,90,'600 km polar']].map(([altitude,inclination,label])=><button key={label} disabled={!primary||s.mode!=='sandbox'||altitude===35786000&&primary.id!=='earth'} onClick={()=>run(()=>sim.edit(d=>{const p=d.bodies.find(x=>x.id===primary.id),sat=spacecraftAt(p,{altitude,inclination},0,d.jd);sat.id=uid('satellite');sat.name=p.name+' '+label;d.bodies.push(sat);}))}>{label}</button>)}<small>GEO altitude is Earth-specific. These presets create SI state vectors, rather than moving an existing vehicle.</small></div></details></div>;
}
export function ReplayTools({run}){
 const sim=useSimStore(),s=sim.scenario,replay=useReplayStore(),input=useRef();
 return <div className="stack"><h2>Mission replay</h2><span className="badge">{replay.playback?'Recorded replay':s.ephemeris?'Ephemeris playback':'Current simulation'}</span><small>Exact captured snapshots, up to 240 frames / 32 MiB / 1,000 bodies. Scrubbing selects a recorded physical state. No invented intermediate states or arbitrary rewind.</small>
 <div className="grid"><button disabled={replay.playback} onClick={()=>{if(replay.recording)replay.stop();else{replay.start();replay.capture(s);}}}>{replay.recording?'Stop recording':'Record snapshots'}</button><button disabled={!replay.frames.length||replay.playback} onClick={()=>run(enterReplay)}>Open replay</button></div><Readouts values={[['Snapshots',replay.frames.length],['Storage estimate',fmt(replay.bytes/1024/1024,2)+' MiB']]}/>
 {replay.playback&&<><div className="row"><button onClick={()=>useReplayStore.setState({playing:!replay.playing})}>{replay.playing?'Pause replay':'Play replay'}</button><button onClick={exitReplay}>Return to Live</button></div><Field>Recorded frame {replay.index+1} / {replay.frames.length}<input aria-label="Recorded snapshot scrubber" type="range" min="0" max={Math.max(0,replay.frames.length-1)} value={replay.index} onChange={e=>replayFrame(+e.target.value)}/></Field><small>{fromJulianDate(replay.frames[replay.index].scenario.jd).toISOString()} · physics edits are locked.</small>
 <details><summary>Jump to recorded event</summary><div className="stack">{replay.frames.flatMap((f,i)=>f.scenario.events.filter(e=>!replay.frames.slice(0,i).some(previous=>previous.scenario.events.some(p=>p.id===e.id))).map(e=>({e,i}))).slice(-40).map(({e,i})=><button key={e.id} onClick={()=>replayFrame(i)}>{e.kind} · {e.message}</button>)}</div></details></>}
 {replay.error&&<p role="alert" className="warning">! {replay.error}</p>}<div className="row"><button disabled={!replay.frames.length} onClick={()=>download(new Blob([JSON.stringify({version:1,name:s.name,frames:replay.frames})],{type:'application/json'}),'orrery-replay.json')}>Export replay</button><button disabled={replay.playback} onClick={()=>input.current.click()}>Import replay</button></div>
 <input type="file" ref={input} accept=".json,application/json" className="sr-only" aria-label="Import recorded replay" onChange={e=>{const file=e.target.files[0];if(file)run(async()=>{if(file.size>32*1024*1024)throw new Error('Replay exceeds 32 MiB');replay.load(JSON.parse(await file.text()));});e.target.value='';}}/>
 {s.ephemeris&&<small>Ephemeris coverage: {fromJulianDate(s.ephemeris.startJD).toISOString()} → {fromJulianDate(s.ephemeris.endJD).toISOString()}. Use the simulation clock to advance through loaded vectors.</small>}
 </div>;
}
