import './universe.css';
import immersive from './immersive.css?inline';
import styled,{createGlobalStyle} from 'styled-components';
export const GlobalStyle=createGlobalStyle`
 :root{color-scheme:dark;font-family:Inter,"Segoe UI",Helvetica,Arial,sans-serif;color:#dce1e8;background:#080b10;font-size:calc(13px * var(--text-scale,1));--border:#242b35;--surface:#11151c;--muted:#828c9b;--accent:#e3b775;--panel-width:328px}
 *{box-sizing:border-box}body{margin:0;overflow:hidden}button,input,select,textarea{font:inherit;color:inherit}button{display:inline-flex;justify-content:center;align-items:center;gap:7px;cursor:pointer;border:1px solid var(--border);border-radius:6px;background:#191e27;padding:8px 11px;min-height:34px;transition:background .16s,border-color .16s,color .16s}
 button:hover:not(:disabled){background:#262e39;border-color:#566172;color:#fff}button:disabled{opacity:.38;cursor:not-allowed}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid #e3b775;outline-offset:3px}
 input,select,textarea{background:#0c1016;border:1px solid #303846;border-radius:5px;padding:8px 9px;min-width:0;width:100%}input[type=checkbox]{width:15px;height:15px;accent-color:var(--accent)}input[type=range]{padding:0;accent-color:var(--accent);height:4px}input[type=color]{height:32px;padding:2px}textarea{resize:vertical;font-family:Consolas,monospace}
 h1,h2,h3,p{margin:0}h1{font-size:18px;font-weight:600;letter-spacing:.18em}h2{font-size:21px;font-weight:550;letter-spacing:-.03em}h3{font-size:12px;font-weight:550}small,.muted{color:var(--muted)}small{font-size:11px;line-height:1.65}a{color:#d9bb8d;overflow-wrap:anywhere}p{line-height:1.7}
 .mono,input[type=number],.metric{font-family:"SFMono-Regular",Consolas,monospace;font-variant-numeric:tabular-nums}
 .eyebrow{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#929eaf}.row{display:flex;align-items:center;gap:8px}.wrap{flex-wrap:wrap}.spread{justify-content:space-between}.stack{display:grid;gap:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.triple{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}
 .divider{border-top:1px solid var(--border);margin:8px 0}.active{border-color:#746045;background:#30281e;color:#efd1a3}.warning{color:#edbd75}.error{color:#f39b94}.success{color:#8bb6a1}.section{border-top:1px solid var(--border);padding-top:18px;margin-top:4px}
 details{border-top:1px solid var(--border);padding-top:6px}details>summary{cursor:pointer;padding:10px 0;font-size:12px;font-weight:550}details[open]>summary{margin-bottom:10px}
 dl{margin:0;display:grid;grid-template-columns:1fr auto;gap:12px 10px;font-size:12px}dt{color:var(--muted)}dd{margin:0;text-align:right;font-family:Consolas,monospace;overflow-wrap:anywhere}
 .badge{border:1px solid #3b4553;border-radius:4px;padding:4px 7px;font-size:9px;text-transform:uppercase;letter-spacing:.07em;white-space:nowrap}.body-label{background:#090d13a0;border:1px solid #ffffff13;border-radius:3px;font:10px Consolas,monospace;padding:3px 7px;min-height:20px;white-space:nowrap;color:#c0c8d4}.body-label.selected{color:#e5c697;border-color:#8b7046}
 .canvas-fallback{display:grid;place-items:center;height:100%;color:#91a0b4;font-size:13px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
 .toolbar-button{position:relative;width:44px!important;height:46px;padding:0;border:0;background:transparent;color:#788596}.toolbar-button.active{background:#29241d;color:#e3b775}.toolbar-button.active:before{content:"";position:absolute;left:-9px;top:12px;bottom:12px;width:2px;background:#e3b775}
 .toolbar-label{position:absolute;left:54px;white-space:nowrap;background:#242b36;border:1px solid #434d5a;padding:7px 10px;pointer-events:none;opacity:0;border-radius:4px;color:#e3e7ed;font-size:11px;z-index:90}.toolbar-button:hover .toolbar-label,.toolbar-button:focus-visible .toolbar-label{opacity:1}
 .rail-label{font-size:8px;letter-spacing:.11em;color:#586473;text-transform:uppercase;text-align:center;margin:10px 0 2px}.rail-bottom{margin-top:auto;display:grid;gap:7px}.rail-bottom button{min-width:0;padding:8px;border:0;background:transparent}
 .event{border-left:2px solid #8e7550;padding:8px 12px;font-size:11px;line-height:1.65;background:#ffffff02}.event .eyebrow{font-size:9px}.chart{width:100%;height:75px;border-bottom:1px solid var(--border)}.chart-label{font-size:10px;color:var(--muted)}
 .catalog-item{padding:0;text-align:left;display:flex;flex-direction:column;align-items:stretch;overflow:hidden;background:#141a23;gap:0}.catalog-item:hover{border-color:#b69767}.catalog-copy{display:grid;gap:7px;padding:15px}.catalog-item strong{font-size:14px;font-weight:550}.catalog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
 .overlay{position:absolute;inset:0;background:#02050bd9;backdrop-filter:blur(9px);z-index:70;display:grid;place-items:center}.high-contrast{--muted:#c2ccd6;--border:#63788a;--surface:#05080d}.camera-readout{position:absolute;bottom:195px;left:92px;font:9px Consolas,monospace;color:#657486;pointer-events:none}
 .mission-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.metric{font-size:20px;color:#e0e6ef;letter-spacing:-.045em}.telemetry-cell{border-bottom:1px solid var(--border);padding:9px 0 14px}.telemetry-cell small{font-size:10px;letter-spacing:.08em;text-transform:uppercase}
 .brand{display:flex;align-items:center;gap:13px}.brand-mark{color:#e3b775;display:grid;place-items:center;width:31px}.brand-sub{font-size:8px!important;letter-spacing:.22em;color:#717e91!important}.header-divider{height:24px;width:1px;background:#303640;margin:0 12px}.project-title{font-size:11px;color:#8995a4;max-width:170px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
 .mode-switch{padding:3px;border:1px solid #2c333d;background:#0a0e14;border-radius:7px;display:flex;gap:2px}.mode-switch button{border:0;background:transparent;padding:6px 15px;min-height:30px;font-size:11px;color:#8995a6}.mode-switch button.active{background:#28241f;color:#ebc792;box-shadow:inset 0 0 0 1px #534532}
 .command-button{color:#91a0b0;font-size:11px;background:transparent}.command-button kbd{font-size:9px;padding:2px 5px;background:#ffffff08;border:1px solid #303844;border-radius:3px;margin-left:10px}
 .icon-button{padding:7px;min-width:32px;background:transparent}.status-dot,.live-dot{height:5px;width:5px;border-radius:50%;background:#89b3a0;display:inline-block;flex-shrink:0}.live-dot{margin-left:auto}.text-separator{margin:0 7px;color:#3e4957}
 .viewport-stage{position:absolute;inset:64px 0 179px 68px;background:#030509;transition:right .25s}.viewport-stage[data-panel="true"]{right:var(--panel-width)}.viewport-heading{position:absolute;top:94px;left:98px;pointer-events:none;z-index:5}.viewport-heading h2{font-size:30px;font-weight:450;letter-spacing:-.025em;margin:7px 0 10px;color:#f1f2f5}.viewport-heading>span{font:10px Consolas,monospace;color:#68788c}
 .viewport-actions{position:absolute;top:86px;right:calc(var(--panel-width) + 22px);display:flex;gap:4px;z-index:20;border:1px solid #2b3441;background:#0d131bcc;border-radius:6px;padding:4px}.workspace-no-panel .viewport-actions{right:24px}.viewport-actions button{background:transparent;border:0;min-width:32px;height:32px;padding:5px;color:#8090a1}.viewport-actions button.active{color:#e7bf88;background:#28231c}.viewport-actions>span{width:1px;background:#2b3441;margin:6px 3px}
 .viewport-guide{position:absolute;bottom:198px;left:50%;transform:translateX(-50%);display:flex;gap:20px;pointer-events:none;color:#526173;white-space:nowrap;font-size:10px}.viewport-guide>span{display:flex;align-items:center;gap:6px}kbd{font:9px Consolas,monospace;border:1px solid #39424f;padding:1px 4px;border-radius:3px}
 .selection-heading{display:flex;align-items:center;gap:13px;margin:2px 0 4px}.selection-heading h2{margin-top:5px}.selection-heading>button{margin-left:auto}.panel-tabs{display:flex;border-bottom:1px solid var(--border);gap:18px;margin:0 -20px;padding:0 20px;position:sticky;top:-20px;background:#10151df5;z-index:2}
 .panel-tabs button{background:transparent;border:0;border-radius:0;padding:12px 0;font-size:11px;color:#7d8a9b}.panel-tabs button.active{color:#edc991;box-shadow:inset 0 -2px #e3b775}.overview-content{display:grid;gap:22px}.object-description{font-size:13px;line-height:1.85;color:#98a5b6}
 .overview-metrics{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:17px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.overview-metrics span{font-size:8px;letter-spacing:.1em;color:#7c8b9e;display:block;margin-bottom:8px}.overview-metrics strong{font-size:20px;font-weight:450;letter-spacing:-.025em;font-variant-numeric:tabular-nums}.overview-metrics small{font-size:10px}
 .section-title{display:flex;align-items:center;gap:8px;margin-bottom:17px;color:#aebacc}.section-title h3{font-size:11px;font-weight:500}.section-title svg{color:#8b7660}.count{margin-left:auto;color:#758295;font:10px Consolas,monospace}.satellite-list{display:grid;gap:6px}.satellite-list button{justify-content:flex-start;background:#ffffff02;border:1px solid #ffffff06;padding:9px;font-size:11px}.satellite-list button svg{margin-left:auto;color:#627386}
 .primary-button{background:#dfb877;border-color:#dfb877;color:#111820;font-weight:600;min-height:39px}.primary-button:hover:not(:disabled){background:#f2ce94;color:#111820;border-color:#f2ce94}.secondary-button{border-color:#3b4553;min-height:39px;font-size:11px}.model-note{display:flex;gap:8px;font-size:10px;line-height:1.6;color:#697d95;padding-top:14px;border-top:1px solid var(--border)}.model-note svg{flex-shrink:0;margin-top:2px}.property-editor{display:grid;gap:15px}.property-editor h2{font-size:17px}
 .planet-swatch{display:inline-block;flex-shrink:0;width:var(--size);height:var(--size);border-radius:50%;background-color:var(--planet-color,#798797);background-size:auto 100%;background-position:45% 50%;box-shadow:inset -10px -3px 13px #000d,inset 1px 1px 2px #ffffff3b;position:relative}.planet-swatch.is-star{box-shadow:0 0 17px #c8822728,inset -6px -3px 13px #0004}.has-rings:after{content:"";position:absolute;inset:30% -36%;border:4px solid #a9987566;border-radius:50%;transform:rotate(-25deg)}
 .body-navigator{position:absolute;bottom:76px;left:68px;right:0;height:103px;border-top:1px solid #252c36;background:#10151df7;z-index:25}.navigator-heading{height:29px;display:flex;align-items:center;gap:24px;padding:0 25px;border-bottom:1px solid #ffffff04}.navigator-heading .eyebrow{font-size:8px}.navigator-filters{display:flex;gap:18px}.navigator-filters button{border:0;background:transparent;min-height:26px;padding:0;font-size:10px;color:#67788d}.navigator-filters button.active{color:#deb985}.navigator-count{margin-left:auto;color:#516074;font:9px Consolas,monospace}
 .body-strip{display:flex;align-items:stretch;gap:4px;padding:6px 15px;height:74px;overflow-x:auto;scrollbar-width:none}.body-strip::-webkit-scrollbar{display:none}.body-tile{background:transparent;border:1px solid transparent;min-width:85px;flex:1;max-width:146px;position:relative;flex-direction:column;gap:5px;border-radius:5px;padding:4px 10px;font-size:10px;color:#7f8fa3}.body-tile.selected{background:#26231e;border-color:#514431;color:#e6c38f}.body-tile:hover{background:#1b222d}.selection-dot{position:absolute;top:8px;right:8px;width:4px;height:4px;background:#e3b775;border-radius:50%}.navigator-empty{font-size:11px;color:#6d7f94;padding:16px}
 .scenario-art{height:128px;background:#080d14;position:relative;display:grid;place-items:center;overflow:hidden}.scenario-art>.planet-swatch{transform:translate(25px,13px);width:100px;height:100px;box-shadow:inset -28px -10px 30px #000}.scenario-art>svg{position:absolute;bottom:13px;left:15px;color:#af9a7b}.art-orbit{position:absolute;width:240px;height:70px;border:1px solid #8f9fb328;border-radius:50%;transform:rotate(-24deg)}.art-orbit.second{width:330px;height:105px}.extreme-art{background:#090908}.extreme-art>.planet-swatch{background-image:none!important;background:#000;box-shadow:0 0 0 2px #c7925630,0 0 30px #c5802544}
 .schematic-art>svg{position:static;width:100%;height:100%;}
 .empty-state{display:grid;justify-items:start;gap:16px;padding:18px 0;color:#91a0b1}.settings-group{display:grid;gap:16px}.time-controls .play-button{background:#dec08c;color:#151a22;border-color:#dec08c}.time-presets{display:flex;gap:4px}.time-presets button{background:transparent;border:0;color:#738398;font-size:10px;padding:4px 6px;min-height:25px}.time-presets button.active{color:#e9c68d;background:#28231d}
 .flight-status{display:grid;gap:10px;padding:15px;border:1px solid #364238;background:#141c19;border-radius:6px}.flight-status .mono{font-size:10px;color:#81998d}.flight-status strong{text-transform:capitalize;font-size:15px;font-weight:500}.flight-progress{display:flex;gap:3px}.flight-progress span{height:3px;flex:1;background:#2c3a32}.flight-progress .complete{background:#91b59d}.placement-banner{position:absolute;left:50%;top:150px;transform:translateX(-50%);display:flex;gap:12px;align-items:center;background:#252016;border:1px solid #77623d;padding:10px 14px;border-radius:6px;z-index:45;font-size:12px;color:#dfc08e}.placement-banner button{font-size:10px;min-height:26px;padding:4px 7px}.placement-banner span{white-space:nowrap}
 @media(min-width:1600px){:root{--panel-width:360px}.viewport-stage{bottom:189px}.body-navigator{height:113px}.body-strip{height:83px}.body-tile{gap:7px}}
 @media(max-width:1100px){:root{--panel-width:300px}.project-title,.header-divider,.mode-label,.time-presets{display:none!important}.viewport-heading{left:87px}.viewport-guide{left:40%;gap:12px}.catalog-grid{grid-template-columns:1fr 1fr}}
 @media(max-width:800px){:root{--panel-width:0px}button{min-height:40px}.hide-mobile{display:none!important}.viewport-stage,.viewport-stage[data-panel="true"]{inset:108px 0 155px 0}.viewport-heading{top:128px;left:20px}.viewport-heading h2{font-size:24px}.viewport-actions{top:121px;right:12px;gap:0}.viewport-actions button{min-width:29px;width:29px}.viewport-guide{display:none}.camera-readout{display:none}.body-navigator{left:0;bottom:67px;height:88px}.navigator-heading{height:25px;padding:0 14px}.body-strip{height:62px;padding:4px 8px}.body-tile{min-width:75px;gap:3px;font-size:9px}.body-tile .planet-swatch{width:27px;height:27px}.navigator-count{display:none}.catalog-grid{grid-template-columns:1fr 1fr;gap:9px}.catalog-copy{padding:11px}.catalog-item strong{font-size:12px}.scenario-art{height:100px}.mode-switch button{padding:5px 9px}.command-button kbd{display:none}.brand{gap:8px}.brand-mark{width:24px}.overview-content{gap:18px}.panel-tabs{top:-16px;margin:0 -16px;padding:0 16px}.mission-grid{grid-template-columns:1fr 1fr}.rail-label,.toolbar-label,.rail-bottom{display:none!important}.toolbar-button{height:36px!important;width:38px!important}.toolbar-button.active:before{left:8px;right:8px;top:auto;bottom:0;width:auto;height:2px}}
 @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important}}.reduce-motion *{animation:none!important;transition:none!important}
 ${immersive}
`;
export const Shell=styled.main`width:100vw;height:100dvh;position:relative;overflow:hidden`;
export const Header=styled.header`position:absolute;top:0;left:0;right:0;height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 23px;border-bottom:1px solid #262d38;background:#11161e;gap:15px;z-index:35;.brand-sub{margin-top:3px}@media(max-width:800px){height:62px;padding:0 12px;gap:8px;.brand-sub{display:none}h1{font-size:15px}}`;
export const Glass=styled.section`background:var(--surface);border:1px solid var(--border);border-radius:7px;`;
export const Rail=styled.nav`position:absolute;top:64px;bottom:76px;left:0;width:68px;padding:10px 11px;display:flex;flex-direction:column;gap:6px;background:#10151d;border-right:1px solid #252d39;z-index:40;@media(max-width:800px){top:62px;bottom:auto;left:0;right:0;width:auto;height:46px;flex-direction:row;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;padding:4px 9px;gap:3px;border-bottom:1px solid #252d39}`;
export const InspectorPanel=styled.section`position:absolute;right:0;top:64px;width:var(--panel-width);bottom:179px;overflow:auto;padding:20px;display:flex;flex-direction:column;gap:18px;scrollbar-width:thin;scrollbar-color:#353f4c transparent;background:#10151dfc;border-left:1px solid #252d39;z-index:30;@media(min-width:1600px){bottom:189px}@media(max-width:800px){right:8px;left:8px;top:auto;bottom:162px;width:auto;max-height:44dvh;padding:16px;border:1px solid #35404f;border-radius:12px 12px 7px 7px;box-shadow:0 -10px 45px #0008}`;
export const Field=styled.label`display:grid;gap:6px;font-size:11px;color:#93a0b3;input{font-size:12px}.unit{max-width:70px;font-size:10px}.row input{flex:1}`;
export const Footer=styled.footer`position:absolute;bottom:0;left:0;right:0;height:76px;padding:12px 24px;display:flex;align-items:center;gap:26px;background:#0c1119;border-top:1px solid #2b3240;z-index:40;.clock{min-width:194px}.speed{width:180px;flex:1;max-width:250px}.transport{margin-left:auto;text-align:right;font-size:10px;line-height:1.7}@media(max-width:1100px){gap:16px;.clock{min-width:176px}}@media(max-width:800px){height:67px;padding:9px 12px;gap:12px;.clock{min-width:0;flex:1}.clock .eyebrow{font-size:8px}.clock small,.transport{display:none}.speed{display:grid;width:74px;flex:none;font-size:9px}.clock .mono{font-size:11px!important}.row{gap:4px}button{padding:7px;min-width:32px}.scale-selector{display:none}}`;
export const Notice=styled(Glass)`position:absolute;bottom:200px;left:90px;max-width:min(480px,calc(100vw - 110px));padding:17px 20px;font-size:12px;line-height:1.65;z-index:65;box-shadow:0 12px 45px #0008;@media(max-width:800px){left:12px;bottom:172px;max-width:calc(100vw - 24px)}`;
export const Dialog=styled(Glass)`width:min(900px,calc(100vw - 40px));max-height:86dvh;overflow:auto;padding:25px;box-shadow:0 24px 100px #000b;scrollbar-width:thin;border-color:#354151;@media(max-width:800px){width:calc(100vw - 20px);padding:17px}`;
