import {useState} from 'react';
import {useSimStore} from '../store/useSimStore.js';
import {useExplorerStore} from '../store/useExplorerStore.js';
import {useWhatIfStore} from '../store/useWhatIfStore.js';
import {habitableZone,generateSystem,binarySystem,formationSystem,formationMetrics,placePlanet,STAR_TYPES,equilibriumTemperature} from '../astronomy/systems.js';
import {relativisticCruise,interstellarMission,communicationTimeline,PROPULSION} from '../astronomy/interstellar.js';
import {formatDistance,formatDuration,C} from '../astronomy/coordinates.js';
import {STARS,SYSTEMS} from '../astronomy/catalog.js';
import {scenarioLibrary,download} from '../persistence.js';
import {G,AU,SOLAR_MASS,EARTH_MASS,EARTH_RADIUS,norm,sub} from '../physics/units.js';
import {body} from '../physics/body.js';
import {baseScenario} from '../physics/catalog.js';
import {NumberField,Select,Toggle,Readouts,fmt} from './Fields.jsx';
import {Field} from './styles.js';
import {ScienceTable,metric,stamp,go} from './UniverseShared.jsx';
export function Builder({run,formation=false}){
 const sim=useSimStore(),s=sim.scenario,e=useExplorerStore(),[type,setType]=useState('sun'),[count,setCount]=useState(6),[inner,setInner]=useState(.3*AU),[outer,setOuter]=useState(15*AU),[giants,setGiants]=useState(true),[moons,setMoons]=useState(true),[belt,setBelt]=useState(false),[seed,setSeed]=useState(42),[name,setName]=useState('Hypothetical planet'),[mass,setMass]=useState(EARTH_MASS),[radius,setRadius]=useState(EARTH_RADIUS),[a,setA]=useState(AU),[ecc,setEcc]=useState(0),[i,setI]=useState(0),[M,setM]=useState(0),[separation,setSeparation]=useState(AU),[secondary,setSecondary]=useState(SOLAR_MASS),[architecture,setArchitecture]=useState('circumbinary'),[proto,setProto]=useState(64),[dust,setDust]=useState(600);
 const star=s.bodies.find(b=>b.id===s.view.selected)??s.bodies.find(b=>b.type==='star'),hz=habitableZone(star?.luminosity),period=star?.mass>0?2*Math.PI*Math.sqrt(a**3/(G*(star.mass+mass))):null,metrics=formationMetrics(s);
 const primary=()=>{const next=baseScenario('User-built system');next.bodies=[body({id:'primary',name:'Primary',type:'star',...STAR_TYPES[type],position:[0,0,0]})];next.view.selected='primary';e.editable(next);};
 return <div className="stack"><h2>{formation?'Formation laboratory':'System Builder'}</h2><small className="model-note">{formation?'Simplified educational formation model':'Configured N-body initial conditions'}</small>
 <Select label="Primary preset" value={type} options={Object.keys(STAR_TYPES).map(k=>[k,k==='sun'?'Solar-like':k==='red'?'Red dwarf configuration':'Hot star configuration'])} commit={setType}/><button onClick={()=>run(primary)}>Start with primary star</button>
 {s.mode==='sandbox'&&star?.type==='star'&&<details open><summary>Edit selected primary</summary><div className="stack">{[['mass','Mass','M☉'],['radius','Radius','R☉'],['temperature','Temperature','K'],['luminosity','Luminosity','W']].map(([k,label,u])=><NumberField key={k} label={label} value={star[k]} unit={u} commit={value=>run(()=>sim.edit(d=>d.bodies.find(b=>b.id===star.id)[k]=value))}/>)}<NumberField label="Rotation period" value={star.spin.period} unit="d" units={['s','d']} commit={v=>run(()=>sim.edit(d=>d.bodies.find(b=>b.id===star.id).spin.period=v))}/></div></details>}
 {!formation&&<><h3>Hypothetical planet / moon</h3><Field>Name<input value={name} onChange={x=>setName(x.target.value)}/></Field><div className="grid"><NumberField label="Mass" value={mass} unit="M⊕" units={['kg','M⊕','M☉']} commit={setMass}/><NumberField label="Radius" value={radius} unit="R⊕" units={['m','km','R⊕']} commit={setRadius}/><NumberField label="Semi-major axis" value={a} unit="AU" units={['m','km','AU']} commit={setA}/><NumberField label="Eccentricity" value={ecc} commit={setEcc}/><NumberField label="Inclination" value={i} unit="deg" units={['deg','rad']} commit={setI}/><NumberField label="Mean anomaly" value={M} unit="deg" units={['deg','rad']} commit={setM}/></div>
 <Readouts values={[['Estimated period',period?formatDuration(period):'Select primary'],['Equilibrium temperature',metric(equilibriumTemperature(star?.luminosity,a),'K')],['Escape velocity',metric(Math.sqrt(2*G*mass/radius),'km/s',1000)],['Hill estimate',star?.mass?formatDistance(a*(1-ecc)*Math.cbrt(mass/(3*star.mass))):'Unknown'],['HZ relationship',hz?(a>=hz.inner&&a<=hz.outer?'Inside simplified zone':'Outside simplified zone'):'Unknown luminosity']]}/>
 <button disabled={s.mode!=='sandbox'||!star} onClick={()=>run(()=>sim.edit(d=>placePlanet(d,{name,mass,radius,a,e:ecc,i,M,parentId:star.id})))}>Add physical body around selected primary</button>
 <Toggle label="Habitable-zone guide" value={s.view.habitableZone} commit={x=>sim.configureView({habitableZone:x})}/><small>{hz?formatDistance(hz.inner)+' – '+formatDistance(hz.outer)+' · '+hz.model:'Select a luminous star.'}</small>
 <details><summary>Generate planetary system</summary><div className="stack"><NumberField label="Planet count · 1–16" value={count} commit={x=>setCount(Math.round(x))}/><NumberField label="Inner orbit" value={inner} unit="AU" commit={setInner}/><NumberField label="Outer orbit" value={outer} unit="AU" commit={setOuter}/><NumberField label="Seed" value={seed} commit={setSeed}/><Toggle label="Allow gas giants" value={giants} commit={setGiants}/><Toggle label="Add giant moons" value={moons} commit={setMoons}/><Toggle label="Add 600 belt tracers" value={belt} commit={setBelt}/><button onClick={()=>run(()=>e.editable(generateSystem({starType:type,count,inner,outer,giants,moons,belt,seed})))}>Generate system</button><small>Eight mutual Hill-radius spacing heuristic. Not guaranteed stable over astronomical timescales.</small></div></details>
 <details><summary>Binary / triple experiment</summary><div className="stack"><NumberField label="Binary separation" value={separation} unit="AU" commit={setSeparation}/><NumberField label="Companion mass" value={secondary} unit="M☉" commit={setSecondary}/><Select label="Architecture" value={architecture} options={['circumbinary','component']} commit={setArchitecture}/><button onClick={()=>run(()=>e.editable(binarySystem({separation,secondaryMass:secondary,architecture})))}>Create barycentric binary</button><button onClick={()=>run(()=>e.editable(binarySystem({separation,secondaryMass:secondary,architecture,triple:true})))}>Hierarchical triple · experimental</button><small>Binary period: {formatDuration(2*Math.PI*Math.sqrt(separation**3/(G*(SOLAR_MASS+secondary))))}. N-body evolution determines stability.</small></div></details>
 <div className="row wrap"><button disabled={s.mode!=='sandbox'||!star} onClick={()=>run(()=>sim.action(star.id,'moon'))}>Circular moon</button><button disabled={s.mode!=='sandbox'||!star} onClick={()=>run(()=>sim.brush(star.id,'ring',300))}>Asteroid belt</button><button disabled={s.mode!=='sandbox'||!star} onClick={()=>run(()=>sim.spawn('comet',star.position.map((v,k)=>v+(k===0?a:0)),star.velocity.map((v,k)=>v+(k===1?Math.sqrt(G*star.mass/a)*.7:0))))}>Eccentric comet</button><button disabled={s.mode!=='sandbox'} onClick={()=>run(()=>useWhatIfStore.getState().begin())}>What-If branch</button></div></>}
 {formation&&<><NumberField label="Resolved planetesimals · 8–256" value={proto} commit={x=>setProto(Math.round(x))}/><NumberField label="Dust tracers · 0–5000" value={dust} commit={x=>setDust(Math.round(x))}/><button onClick={()=>run(()=>{e.editable(formationSystem({count:proto,dust,seed}));go('formation');})}>Create disk</button><Readouts values={[['Resolved bodies',metrics.count],['Disk mass',metric(metrics.mass,'M⊕',EARTH_MASS)],['Largest body',metrics.largest?.name??'None'],['Largest mass',metric(metrics.largest?.mass,'M⊕',EARTH_MASS)],['Unbound bodies',metrics.ejected],['Retained merge events',metrics.collisions]]}/><small>Physical-radius merging conserves mass and momentum. Dust is non-sourcing. No gas dynamics, chemistry, migration or radiation feedback.</small></>}
 <button onClick={()=>run(()=>scenarioLibrary('save',s))}>Save system</button>{e.solar&&<button onClick={()=>run(()=>e.restoreSolar())}>Restore original simulation</button>}</div>;
}
export function InterstellarPlanner({run}){
 const s=useSimStore(x=>x.scenario),explorer=useExplorerStore(),[origin,setOrigin]=useState('body:earth'),[destination,setDestination]=useState('hyg-70666'),[propulsion,setPropulsion]=useState('Custom'),[speed,setSpeed]=useState(.1*C),[mass,setMass]=useState(1000),[acceleration,setAcceleration]=useState(0),[deceleration,setDeceleration]=useState(0),[reply,setReply]=useState(0);
 const hostCatalog=SYSTEMS.find(x=>x.id===s.bodies.find(b=>b.type==='star')?.metadata?.catalogId),offset=hostCatalog?.position??[0,0,0],baselineBodies=explorer.solar?.scenario.bodies??[],activeIds=new Set(s.bodies.map(b=>b.id));
 const entries=[...s.bodies.filter(b=>!b.disrupted).map(b=>({...b,id:'body:'+b.id,position:b.position.map((x,k)=>x+offset[k])})),...baselineBodies.filter(b=>!activeIds.has(b.id)).map(b=>({...b,id:'body:'+b.id})),...STARS.filter(x=>['hyg-0','hyg-70666','hyg-71456','hyg-32263','hyg-87665','hyg-118720'].includes(x.id)),...SYSTEMS],options=entries.map(x=>[x.id,x.name]),from=entries.find(x=>x.id===origin)??entries[0],to=entries.find(x=>x.id===destination),distance=from&&to?norm(sub(to.position,from.position)):null,concept=PROPULSION.find(x=>x[0]===propulsion);let result=null,error='';try{if(distance!=null)result=interstellarMission({distance,speed,mass,acceleration,deceleration});}catch(e){error=e.message;}let timeline=null;try{if(result)timeline=communicationTimeline(s.jd,distance,reply);}catch(e){error=e.message;}
 return <div className="stack"><h2>Interstellar mission</h2><Select label="Origin" value={from?.id??origin} options={options} commit={setOrigin}/><Select label="Destination" value={destination} options={options.filter(([id])=>id!==from?.id)} commit={setDestination}/><Select label="Propulsion concept" value={propulsion} options={PROPULSION.map(([x,status])=>[x,x+' · '+status])} commit={name=>{setPropulsion(name);setSpeed(PROPULSION.find(x=>x[0]===name)[2]);}}/><small>{concept?.[3]}</small>
 <NumberField label="Requested cruise speed" value={speed} unit="km/s" units={['m/s','km/s']} commit={setSpeed}/><div className="row wrap">{[.01,.05,.1,.25,.5,.75,.9,.99].map(beta=><button key={beta} onClick={()=>setSpeed(beta*C)}>{beta}c</button>)}</div><NumberField label="Spacecraft mass" value={mass} unit="kg" commit={setMass}/><NumberField label="Proper acceleration · m/s² (0 = no ramps)" value={acceleration} commit={setAcceleration}/><NumberField label="Proper deceleration · m/s²" value={deceleration} commit={setDeceleration}/>
 {error&&<p role="alert" className="warning">{error}</p>}{result&&<><Readouts values={[['Distance',formatDistance(distance)],['Peak β',fmt(result.beta,5)],['Lorentz factor',fmt(result.gamma,5)],['Earth-frame time',formatDuration(result.earthTime)],['Traveler proper time',formatDuration(result.properTime)],['One-way communication',formatDuration(result.oneWay)],['Round trip',formatDuration(result.roundTrip)],['Peak kinetic energy',metric(result.kineticEnergy,'J')],['Energy lower bound',metric(result.totalEnergyLowerBound,'J')],['Profile',result.profile]]}/>
 <h3>Velocity / time comparison</h3><ScienceTable columns={['v/c','Earth time','Proper time','γ']} rows={[.01,.1,.5,.9,.99].map(beta=>{const r=relativisticCruise(distance,beta*C,mass);return [beta,formatDuration(r.earthTime),formatDuration(r.properTime),fmt(r.gamma,4)];})}/><h3>Communication timeline</h3><NumberField label="Reply turnaround" value={reply} unit="s" commit={setReply}/>{timeline&&<Readouts values={[['Message sent',stamp(timeline.sent)],['Signal arrival',stamp(timeline.arrival)],['Possible reply sent',stamp(timeline.replySent)],['Reply arrival',stamp(timeline.replyArrival)]]}/>}<button onClick={()=>download(new Blob([JSON.stringify({origin:from.name,destination:to.name,epochJD:s.jd,propulsion,classification:concept[1],configuration:{distance,speed,mass,acceleration,deceleration},result,timeline,model:'Flat spacetime kinematics; static endpoints; no fuel or feasibility model.'},null,2)],{type:'application/json'}),'interstellar-mission.json')}>Export calculation</button></>}
 <small>Separate flat-spacetime calculation, static endpoints. Proper-acceleration ramps are optional. Cruise speeds are inputs, not capabilities of the selected technology. Catalog-system local coordinates are translated to the catalog host location; preserved Solar System objects remain available. No gravity, fuel, power or stellar-motion model; FTL is rejected. Existing physics remains unchanged.</small></div>;
}
