import {useState,useRef,useEffect} from 'react';
import {wrap} from 'comlink';
import {useSimStore} from '../store/useSimStore.js';
import {useExplorerStore} from '../store/useExplorerStore.js';
import {useCameraStore} from '../store/useCameraStore.js';
import {STARS,catalogOrigin} from '../astronomy/catalog.js';
import {formatDistance,formatDuration,C} from '../astronomy/coordinates.js';
import {communicationTimeline} from '../astronomy/interstellar.js';
import {apparentSky,upcomingEvents,missionAnalyst,sensorReadings,CHALLENGES,validateChallenge} from '../astronomy/analysis.js';
import {workerRequest} from '../analysisWorker.js';
import {loadHorizons} from '../horizons.js';
import {download} from '../persistence.js';
import {DAY,YEAR,norm,sub,add,cross,dot,unit,julianDate,fromJulianDate} from '../physics/units.js';
import {observation,observingStar} from '../physics/observations.js';
import {NumberField,Select,Toggle,Readouts,fmt} from './Fields.jsx';
import {Field} from './styles.js';
import {ScienceTable,metric,stamp,go} from './UniverseShared.jsx';
export function ObservationExplorer({run}){
 const sim=useSimStore(),s=sim.scenario,[observerId,setObserver]=useState(s.bodies.some(b=>b.id==='earth')?'earth':s.bodies[0]?.id),[targetId,setTarget]=useState(s.bodies.some(b=>b.id==='jupiter')?'jupiter':s.bodies[1]?.id),[fov,setFov]=useState(5),[surface,setSurface]=useState(true),[lat,setLat]=useState(0),[lon,setLon]=useState(0);
 const observer=s.bodies.find(b=>b.id===observerId),targets=[...s.bodies,...STARS.filter(x=>['hyg-70666','hyg-32263','hyg-87665'].includes(x.id)).map(x=>({...x,position:sub(x.position,catalogOrigin(s)),radius:x.radius??0,velocity:[0,0,0]}))],target=targets.find(x=>x.id===targetId),star=observer?observingStar(s,observer):null,m=observer&&target?observation(observer,target,star):null,sky=observer?apparentSky(observer,targets,s.jd,{latitude:lat,longitude:lon,surface}):[],timeline=m?communicationTimeline(s.jd,m.distance):null;
 const telescope=wide=>{if(!target||!s.bodies.some(b=>b.id===target.id))throw new Error('Catalog-star telescope targeting unavailable; see derived sky direction');sim.configureView({navigation:{...s.view.navigation,surfaceLatitude:lat,surfaceLongitude:lon}});useCameraStore.getState().request('telescope',{observer:observerId,target:targetId,fov:wide?90:fov});};
 return <div className="stack"><h2>Observation and sky</h2><Select label="Observer" value={observerId??''} options={s.bodies.map(b=>[b.id,b.name])} commit={setObserver}/><Select label="Target" value={targetId??''} options={targets.filter(b=>b.id!==observerId).map(b=>[b.id,b.name])} commit={setTarget}/><Select label="Telescope FOV" value={String(fov)} options={[30,10,5,1,.5,.1].map(x=>[String(x),x+'°'])} commit={x=>setFov(+x)}/><Toggle label="Surface-local horizon" value={surface} commit={setSurface}/><NumberField label="Latitude" value={lat} commit={x=>setLat(Math.max(-90,Math.min(90,x)))}/><NumberField label="Longitude" value={lon} commit={x=>setLon(Math.max(-180,Math.min(180,x)))}/>
 {m&&<Readouts values={[['Distance',formatDistance(m.distance)],['One-way light delay',formatDuration(m.lightTime)],['Round trip',formatDuration(m.lightTime*2)],['Relative speed',target?.source?'Unavailable stellar velocity':metric(m.relativeSpeed,'km/s',1000)],['Angular diameter',target?.radius?metric(m.angularSize*180/Math.PI,'°'):'Unknown radius'],['Light-source model',star?.name??'Unknown'],['Illuminated fraction',target?.type==='star'||m.illuminatedFraction==null?'Self-luminous':metric(m.illuminatedFraction*100,'%')]]}/>}
 <div className="row"><button disabled={!observer||!target||!s.bodies.some(b=>b.id===target.id)} onClick={()=>run(()=>telescope(false))}>Track in telescope</button><button disabled={!observer||!target||!s.bodies.some(b=>b.id===target.id)} onClick={()=>run(()=>telescope(true))}>Full sky · 90°</button></div>
 <svg className="sky-chart" viewBox="0 0 320 180" role="img" aria-label="Calculated observer sky: azimuth and elevation"><path d="M10 170H310M10 90H310M10 10H310M10 10V170" stroke="#475360" fill="none"/><text x="12" y="87">Horizon</text>{sky.filter(x=>x.azimuth!=null).map(x=><g key={x.id}><circle cx={10+x.azimuth/360*300} cy={170-(x.elevation+90)/180*160} r={x.id===targetId?3:1.5} fill={x.id===targetId?'#dcb77e':'#9eafbd'}/>{x.id===targetId&&<text x={15+x.azimuth/360*300} y={165-(x.elevation+90)/180*160}>{x.name}</text>}</g>)}</svg>
 <ScienceTable columns={['Object','Azimuth','Altitude','Light delay']} rows={sky.filter(x=>x.id===targetId||x.name==='Sun'||x.elevation>=0).slice(0,12).map(x=>[x.name,metric(x.azimuth,'°'),metric(x.elevation,'°'),formatDuration(x.distance/C)])}/>
 {timeline&&<details><summary>Communication timing</summary><Readouts values={[['Send',stamp(timeline.sent)],['Arrive',stamp(timeline.arrival)],['Reply arrive',stamp(timeline.replyArrival)]]}/></details>}
 <small>Instantaneous geometric sky and spherical horizon. No retarded ephemeris, aberration, refraction or terrain. Physical radii drive apparent diameter. Catalog stellar directions are static.</small></div>;
}
export function EventFinder({run}){
 const s=useSimStore(x=>x.scenario),[query,setQuery]=useState('closest'),[observer,setObserver]=useState(s.bodies.some(b=>b.id==='earth')?'earth':s.bodies[0]?.id),[target,setTarget]=useState(s.bodies.some(b=>b.id==='mars')?'mars':s.bodies[1]?.id),[duration,setDuration]=useState(YEAR*2),[samples,setSamples]=useState(512),[result,setResult]=useState(null),[busy,setBusy]=useState(false),controller=useRef(null),token=useRef(0);
 useEffect(()=>()=>{token.current++;controller.current?.abort();},[]);
 const search=async()=>{const current=++token.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setResult(null);try{const worker=new Worker(new URL('../physics/worker.js',import.meta.url),{type:'module'}),rpc=wrap(worker),r=await workerRequest(worker,()=>rpc.findEvents(structuredClone(useSimStore.getState().scenario),{query,observerId:observer,targetId:target,duration,samples,maxMs:4000}),{signal:abort.signal});if(token.current===current)setResult(r);}finally{if(token.current===current)setBusy(false);}};
 return <div className="stack"><h3>Bounded Event Finder</h3><Select label="Query" value={query} options={[['closest','Closest approach'],['perigee','Perigee / distance minimum'],['opposition','Opposition in ecliptic longitude'],['conjunction','Conjunction in ecliptic longitude'],['eclipse','Observer shadow entry'],['occultation','Target transit / solar occultation']]} commit={setQuery}/><Select label="Observer / primary" value={observer??''} options={s.bodies.map(b=>[b.id,b.name])} commit={setObserver}/><Select label="Target / occulter" value={target??''} options={s.bodies.filter(b=>b.id!==observer).map(b=>[b.id,b.name])} commit={setTarget}/><NumberField label="Search horizon" value={duration} unit="yr" units={['d','yr']} commit={setDuration}/><NumberField label="Samples · 16–4096" value={samples} commit={v=>setSamples(Math.round(v))}/>
 <div className="row"><button disabled={busy||s.bodies.length<2} onClick={()=>run(search)}>Find next events</button><button disabled={!busy} onClick={()=>{token.current++;controller.current?.abort();setBusy(false);}}>Cancel</button></div>
 {result&&<><small>{result.method} · reached {formatDuration(result.advanced)} of {formatDuration(result.requested)} · {result.complete?'Complete sampled search':'Compute budget reached; partial search'}</small>{result.events.length?result.events.map((event,k)=><div className="event" key={k}><strong>{event.kind}</strong><p>{stamp(event.jd)} · {formatDistance(event.distance)}</p><small>Resolution ± {formatDuration(event.uncertaintySeconds)}. {event.model}</small><button disabled={s.mode!=='reality'} onClick={()=>run(()=>useSimStore.getState().jump(fromJulianDate(event.jd)))}>Jump via approximate initialization</button></div>):<small>No event detected within reached coverage. Narrow events may fall between samples; this is not proof of absence.</small>}</>}
 <small>Cloned worker search. Approximate moon phases are illustrative; these are model events, not certified eclipse forecasts.</small></div>;
}
export function TimeMachine({run}){
 const sim=useSimStore(),s=sim.scenario,[date,setDate]=useState(fromJulianDate(s.jd).toISOString().slice(0,10)),[method,setMethod]=useState('jpl'),[busy,setBusy]=useState(false);
 return <div className="stack"><h2>Time Machine</h2><Readouts values={[['Current epoch',stamp(s.jd)],['Source',s.ephemeris?'Horizons Hermite playback':s.provenance.source==='horizons'?'Horizons initialization, local propagation':s.mode==='reality'?'JPL approximate elements':'Local numerical propagation'],['Provenance',s.provenance.note??'']]}/><Field>UTC date<input type="date" min="1800-01-01" max="2050-12-31" value={date} onChange={x=>setDate(x.target.value)}/></Field><Select label="Initialization" value={method} options={[['jpl','JPL approximate'],['horizons','Horizons state vectors'],['playback','One-day Horizons playback']]} commit={setMethod}/>
 <button disabled={busy} onClick={()=>run(async()=>{setBusy(true);try{useExplorerStore.getState().leave();if(method==='jpl')sim.jump(date);else sim.replace(await loadHorizons(s,{jd:julianDate(date),days:method==='playback'?1:0}));}finally{setBusy(false);}})}>{busy?'Loading…':'Initialize at date'}</button><button onClick={()=>go('replay')}>Recorded simulation</button><small>Date initialization replaces live state and is undoable. Sandbox history exists only in explicitly recorded snapshots. Catalog positions stay at their catalog epoch.</small><EventFinder run={run}/></div>;
}
export function Analyst({run}){
 const sim=useSimStore(),s=sim.scenario,result=missionAnalyst(s,s.view.selected,sim.stats),upcoming=upcomingEvents(s,s.view.selected);
 return <div className="stack"><h2>Mission Analyst</h2><small>{result.model}</small><Readouts values={result.facts.map(x=>[x.label,typeof x.value==='number'?fmt(x.value,5):x.value])}/>{result.suggestions.map((a,k)=><button key={k} onClick={()=>run(()=>{if(a.action==='accuracy')sim.edit(d=>d.settings.stepSeconds=Math.max(.01,d.settings.stepSeconds/2));else go(a.action);})}>{a.label} · apply explicitly</button>)}
 <h3>Upcoming events</h3>{upcoming.map((e,k)=><div className="event" key={k}><strong>{e.kind}</strong><small>{stamp(e.jd)} · {formatDuration((e.jd-s.jd)*DAY)} from now</small><p>{e.message}</p></div>)}{!upcoming.length&&<small>No calculable upcoming event.</small>}
 <Select label="Notification category" value={s.view.notificationCategory??'mission'} options={['mission','science','physics','all']} commit={v=>sim.configureView({notificationCategory:v})}/><Toggle label="Notify newly logged mission events" value={s.view.discoveryNotifications} commit={v=>sim.configureView({discoveryNotifications:v})}/><small>Apsides use the osculating orbit. SOI, eclipses, staging and collisions enter the existing log when detected; future timing is not invented.</small></div>;
}
export function Challenges({run}){
 const s=useSimStore(x=>x.scenario),[kind,setKind]=useState('circular'),[target,setTarget]=useState(s.view.targetId??''),r=validateChallenge(s,s.view.selected,kind,target);
 return <div className="stack"><h2>Orbital challenges</h2><Select label="Challenge" value={kind} options={CHALLENGES} commit={setKind}/><Select label="Rendezvous / binary target" value={target} options={[['','Select target'],...s.bodies.filter(b=>b.id!==s.view.selected).map(b=>[b.id,b.name])]} commit={setTarget}/><p className={r.passed?'success':'model-note'} role="status">{r.passed?'PASS · physical criteria satisfied':'NOT YET · criteria not satisfied'}</p><p>{r.criteria}</p><Readouts values={[['Executed Δv',metric(r.deltaV,'m/s')],['Mission elapsed',formatDuration(r.missionDuration)],['Eccentricity',metric(r.eccentricity)],['Period',r.period?formatDuration(r.period):'Unbound / unknown']]}/><small>{r.model} Render radii and camera positions do not affect scores.</small><button onClick={()=>go('rendezvous')}>Maneuver assistance</button><button onClick={()=>download(new Blob([JSON.stringify({kind,epochJD:s.jd,selected:s.view.selected,target,result:r},null,2)],{type:'application/json'}),'challenge-result.json')}>Export scored state</button></div>;
}
export function Sensors({run}){
 const sim=useSimStore(),s=sim.scenario,[target,setTarget]=useState(s.view.targetId??'earth'),[fov,setFov]=useState(30),b=s.bodies.find(b=>b.id===s.view.selected),r=sensorReadings(s,b?.id,target,fov),stars=STARS.filter(x=>x.id!=='hyg-0'&&x.apparentMagnitude!=null&&x.apparentMagnitude<3),visible=r?stars.filter(star=>{const d=unit(sub(star.position,add(b.position,catalogOrigin(s))));return d.reduce((n,x,k)=>n+x*r.direction[k],0)>Math.cos(fov*Math.PI/360);}):[];
 return <div className="stack"><h2>Sensor view</h2><small>Educational geometric sensors; no hardware noise or attitude-solution algorithm.</small><Select label="Target" value={target} options={s.bodies.filter(x=>x.id!==b?.id).map(x=>[x.id,x.name])} commit={setTarget}/><NumberField label="Optical FOV · degrees" value={fov} commit={v=>setFov(Math.max(.1,Math.min(120,v)))}/>
 {r&&<Readouts values={[['Altimeter',r.altitude==null?'No primary':formatDistance(r.altitude)],['Range finder',r.range?formatDistance(r.range.distance):'No target'],['Range rate',r.range?metric(-r.range.closingSpeed,'m/s'):'No target'],['Sun angle',metric(r.sunAngle*180/Math.PI,'°')],['Sunlight',r.sunlight.state],['Light-source model',r.lightSource],['Bright references in FOV',visible.length],['Tracker geometry',visible.length>=3?'Three or more reference directions':'Insufficient reference geometry'],['Attitude lock','Unavailable: no attitude-determination solver']]}/>}
 <div className="row wrap">{[['forward','Look forward'],['target','Track target'],['earth','Track Earth'],['sun','Track Sun']].map(([mode,label])=><button key={mode} disabled={!b||mode==='target'&&!s.bodies.some(x=>x.id===target)||mode==='earth'&&!s.bodies.some(x=>x.id==='earth')||mode==='sun'&&!s.bodies.some(x=>x.type==='star')} onClick={()=>run(()=>sim.configureView({pip:true,sensorView:{mode,targetId:target,fov}}))}>{label}</button>)}</div><button onClick={()=>sim.configureView({pip:false,sensorView:null})}>Close optical inset</button>
 <svg className="sky-chart" viewBox="0 0 260 180" role="img" aria-label="Geometric proximity projection"><circle cx="130" cy="90" r="70" fill="none" stroke="#536170"/><path d="M60 90H200M130 20V160" stroke="#303b47"/>{b&&s.bodies.filter(x=>x.id!==b.id).slice(0,100).map(x=>{const r=sub(x.position,b.position),range=Math.max(1,b.spacecraft?.range??1e8),d=Math.hypot(r[0],r[1]),factor=70/Math.max(range,d);return <circle key={x.id} cx={130+r[0]*factor} cy={90-r[1]*factor} r={x.id===target?3:1.5} fill={x.id===target?'#dcba89':'#8e9aa6'}/>;})}</svg><small>Radar-style geometry, not RF detection. Objects beyond display range sit on the rim.</small>
 {r&&<><h3>Reference-star geometry</h3><svg className="sky-chart" viewBox="0 0 260 180" role="img" aria-label="Bright reference stars projected into the sensor field of view"><rect x="40" y="15" width="180" height="150" stroke="#506071" fill="none"/>{visible.map(star=>{const d=unit(sub(star.position,add(b.position,catalogOrigin(s)))),east=unit(cross(r.direction,Math.abs(r.direction[2])<.95?[0,0,1]:[0,1,0])),north=unit(cross(east,r.direction)),t=Math.tan(fov*Math.PI/360),f=dot(d,r.direction);return <g key={star.id}><circle cx={130+70*dot(d,east)/(f*t)} cy={90-70*dot(d,north)/(f*t)} r="2" fill="#bbc6cf"/><title>{star.name}</title></g>;})}<text x="46" y="26">{fov}° · geometric references</text></svg><small>{visible.slice(0,6).map(star=>star.name).join(', ')||'No bundled bright star in the current FOV.'}</small></>}<h3>Environment and interior</h3><Select label="Environment" value={s.view.environment??''} options={[['','Off'],['magnetic','Schematic dipole field'],['radiation','Dipole / radiation shells']]} commit={v=>sim.configureView({environment:v||null})}/><button disabled={!b} onClick={()=>run(()=>useCameraStore.getState().request('focus',{id:b.id,mode:'orbit'}))}>Inspect selected object</button><Toggle label="Educational cutaway" disabled={!b||!['planet','moon','dwarf'].includes(b.type)} value={s.view.interior} commit={v=>sim.configureView({interior:v})}/><small>Rocky layers: crust / mantle / outer / inner core. Giant layers: envelope / molecular / metallic hydrogen / core approximation. Fractions are schematic. No collision-radius or force changes; magnetic overlays do not simulate electromagnetic forces.</small></div>;
}
