import {useState,useMemo} from 'react';
import {useSimStore} from '../store/useSimStore.js';
import {useExplorerStore} from '../store/useExplorerStore.js';
import {STARS,SYSTEMS,catalogObject,searchUniverse,metadata} from '../astronomy/catalog.js';
import {formatDistance,galacticCoordinates} from '../astronomy/coordinates.js';
import {derivedOrbit} from '../physics/orbital.js';
import {loadCatalogSystem,habitableZone} from '../astronomy/systems.js';
import {systemCamera,focusCamera} from '../navigation/actions.js';
import {scenarioLibrary,download} from '../persistence.js';
import {AU,DAY,SOLAR_MASS,SOLAR_RADIUS,EARTH_MASS,EARTH_RADIUS,norm} from '../physics/units.js';
import {NumberField,Select,Toggle,Readouts} from './Fields.jsx';
import {Field} from './styles.js';
import {ScienceTable,metric,go} from './UniverseShared.jsx';
export default function UniversePanel({run}){
 const sim=useSimStore(),s=sim.scenario,e=useExplorerStore(),[query,setQuery]=useState(''),[name,setName]=useState(''),[mass,setMass]=useState(EARTH_MASS),[radius,setRadius]=useState(EARTH_RADIUS);
 const results=useMemo(()=>searchUniverse(query,s.bodies,30),[query,s.bodies]),selected=catalogObject(e.selected),system=SYSTEMS.find(x=>x.id===(selected?.systemId??selected?.id??e.systemId)),gal=selected?.position?galacticCoordinates(selected.position):null;
 const focus=x=>{if(x.bodyId){e.leave();focusCamera(x.bodyId);return;}if(x.type==='system'||x.type==='exoplanet'){e.openSystem(x.systemId??x.id);return;}e.enter(x.type==='galaxy'?'group':x.id==='sgr-a'?'milky':'nearby');e.focus(x.id);};
 const solar=e.solar?.scenario??e.baseline?.scenario??s,solarHost=solar.bodies.find(b=>b.id==='sun'),solarPlanets=solar.bodies.filter(b=>b.type==='planet'&&b.parentId==='sun'),solarSystem=solarHost?{id:'solar-system',name:'Solar System',host:solarHost,planets:solarPlanets.map(b=>{const orbit=derivedOrbit(b,solar.bodies,solar.settings).elements;return {name:b.name,radius:b.radius,a:orbit?.a,period:orbit?.period};})}:null;
 const comparisonObject=id=>id==='solar-system'?solarSystem:catalogObject(id);
 const loadFavorite=async f=>{if(['scenario','mission'].includes(f.kind)){const record=(await scenarioLibrary()).find(r=>r.id===f.id);if(!record)throw new Error('Saved scenario no longer exists');e.leave();sim.replace(record.scenario);}else if(f.kind==='camera'){const session=e.sessions.find(r=>r.id===f.id);if(!session)throw new Error('Saved view no longer exists');e.loadSession(session);}else{const x=catalogObject(f.id);if(x)focus(x);else{e.leave();sim.configureView({selected:f.id.replace('body:','')});}}};
 return <div className="stack"><h2>Universe explorer</h2><small className="model-note">{e.active?'CATALOG NAVIGATION · physics preserved and paused':'ACTIVE SIMULATION · separate catalog layer'}</small>
 <div className="row wrap"><button onClick={()=>run(()=>{e.leave();if(e.solar)e.restoreSolar();systemCamera();})}>Solar System</button>{[['nearby','Nearby stars'],['milky','Milky Way'],['group','Local Group']].map(([id,label])=><button key={id} onClick={()=>run(()=>e.overview(id))}>{label}</button>)}<button onClick={()=>run(()=>{e.leave();go('observe-universe');})}>Observation</button><button onClick={()=>run(()=>{e.leave();go('time-machine');})}>Time Machine</button></div>
 {e.active&&<button onClick={()=>run(()=>e.leave())}>Return to preserved simulation</button>}{e.solar&&<button onClick={()=>run(()=>e.restoreSolar())}>Restore original simulation</button>}
 <div className="row"><button disabled={e.index<=0} onClick={()=>run(()=>e.travel(-1))}>← History</button><button disabled={e.index>=e.history.length-1} onClick={()=>run(()=>e.travel(1))}>History →</button></div>
 <Field>Search objects, systems and galaxies<input aria-label="Universe search" value={query} onChange={x=>setQuery(x.target.value)} placeholder="Earth, Europa, Proxima, TRAPPIST-1…"/></Field>
 <div className="universe-results">{results.map(x=><div className="row spread" key={x.id}><button className="object-result" onClick={()=>{if(x.bodyId){e.leave();sim.configureView({selected:x.bodyId,panel:'inspector'});}else e.select(x.id);}}><strong>{x.name}</strong><small>{x.type} · {x.context??(x.position?formatDistance(norm(x.position)):'Distance unknown')}</small></button><button aria-label={'Focus '+x.name} onClick={()=>run(()=>focus(x))}>Focus</button></div>)}</div>
 <Select label="Exoplanet system" value={e.systemId??''} options={[['','Choose system'],...SYSTEMS.map(s=>[s.id,s.name])]} commit={id=>run(()=>{if(id)e.openSystem(id);})}/>
 {selected&&<><h3>{selected.name}</h3><span className="eyebrow">{selected.massStatus??selected.status??'Catalog value'} · {selected.source}</span><Readouts values={[['Type',selected.spectralType??selected.host?.spectralType??selected.type],['Distance',selected.position?formatDistance(norm(selected.position)):'Unknown'],['Mass',metric(selected.mass??selected.host?.mass,'M☉',SOLAR_MASS)],['Radius',metric(selected.radius??selected.host?.radius,'R☉',SOLAR_RADIUS)],['Radius source',selected.radiusStatus??(selected.radius||selected.host?.radius?'Catalog value':'Unknown')],['Temperature',metric(selected.temperature??selected.host?.temperature,'K')],['Luminosity',metric(selected.luminosity??selected.host?.luminosity,'L☉',3.828e26)],['Luminosity source',selected.luminosityStatus??'NASA bolometric composite'],['Apparent magnitude',metric(selected.apparentMagnitude)],['Absolute magnitude',metric(selected.absoluteMagnitude)],['Galactic longitude',metric(gal?.longitude,'°')],['Galactic latitude',metric(gal?.latitude,'°')],['Known system',selected.id==='hyg-0'?'Solar System':selected.systemId??(selected.planets?selected.name:'Not available in bundled dataset')]]}/><small>{selected.description}</small><button onClick={()=>run(()=>focus(selected))}>Focus explicitly</button>{selected.systemId&&<button onClick={()=>run(()=>e.openSystem(selected.systemId))}>Open planetary system</button>}<button onClick={()=>run(()=>e.favorite(selected.id,selected.name,selected.type))}>{e.favorites.some(x=>x.id===selected.id)?'Unfavorite':'Favorite'}</button></>}
 {e.section==='system'&&system&&<><h3>{system.name} parameter model</h3><Toggle label="Show approximate habitable zone" value={e.hz} commit={x=>e.update({hz:x})} title="Approximate luminosity-based liquid-water zone; not proof of habitability."/><small>Catalog orbit scale; coplanar geometry and phases are illustrative. Missing mass/radius require configured fallback values.</small><ScienceTable columns={['Planet','a AU','Period d','Radius R⊕','Mass M⊕','Mass source','Radius source','e','T eq K','Discovery']} rows={system.planets.map(p=>[p.name,metric(p.a,'',AU),metric(p.period,'',DAY),metric(p.radius,'',EARTH_RADIUS),metric(p.mass,'',EARTH_MASS),p.massStatus,p.radiusStatus,metric(p.e),metric(p.temperature),p.discoveryMethod+' · '+p.discoveryYear])}/><NumberField label="Unknown planet mass fallback" value={mass} unit="M⊕" units={['kg','M⊕']} commit={setMass}/><NumberField label="Unknown radius fallback" value={radius} unit="R⊕" units={['m','R⊕']} commit={setRadius}/><button onClick={()=>run(()=>e.editable(loadCatalogSystem(system,{unknownMass:mass,unknownRadius:radius})))}>Create editable scenario</button><small>Includes catalog minimum masses and mass-radius estimates. Normal N-body evolution determines behavior.</small></>}
 <details><summary>Cosmic scale and layers</summary><div className="stack"><div className="row wrap">{[['Earth radius',6371000],['Moon distance',384400000],['1 AU',AU],['Solar System',100*AU],['Proxima distance',4.24*9460730472580800],['Milky Way diameter',100000*9460730472580800],['Andromeda distance',2.5e6*9460730472580800]].map(([label,d])=><button key={label} onClick={()=>run(()=>{const section=d>1e22?'group':d>1e19?'milky':'nearby';e.enter(section);e.scale(d);})}>{label}</button>)}</div><Field>Extent · {formatDistance(e.liveSpan??e.span)}<input aria-label="Cosmic scale" type="range" min="3" max="23" step=".1" value={Math.log10(e.liveSpan??e.span)} onChange={x=>run(()=>{const span=10**+x.target.value;if(!e.active)e.enter('nearby');const section=span>1e22?'group':span>1e19?'milky':'nearby';if(e.section!==section)e.enter(section);e.scale(span);})}/></Field><Toggle label="Relevant labels" value={e.labels} commit={labels=>e.update({labels})}/><Toggle label="Educational explanations" value={e.educational} commit={educational=>e.update({educational})}/>{e.educational&&<p>AU is a defined orbital-distance unit. Light-years measure distance traveled in one Julian year. Parsecs derive from parallax. Camera travel is navigation, never physical FTL. Galaxy arms are schematic.</p>}<small>WASDQE cancels focus and enters Free. Drag looks; wheel adjusts speed. Orbit supports drag/zoom/pan. Shift boosts; Ctrl slows.</small></div></details>
 <details><summary>Favorites and sessions</summary><div className="stack">{e.favorites.map(f=><div className="row" key={f.id}><button onClick={()=>run(()=>loadFavorite(f))}>{f.label}</button><button aria-label={'Unfavorite '+f.label} onClick={()=>run(()=>e.favorite(f.id,f.label,f.kind))}>×</button></div>)}<Field>Session / favorite name<input value={name} onChange={x=>setName(x.target.value)}/></Field><button disabled={!e.active} onClick={()=>run(()=>e.saveSession(name))}>Save catalog viewpoint</button><button onClick={()=>run(async()=>{const id=await scenarioLibrary('save',s);e.favorite(id,name||s.name,s.bodies.some(b=>b.rocket)?'mission':'scenario');})}>Favorite simulation snapshot</button>
 {e.sessions.map(r=><div className="row wrap" key={r.id}><button onClick={()=>run(()=>e.loadSession(r))}>{r.name}</button><button onClick={()=>run(()=>e.favorite(r.id,r.name,'camera'))}>Favorite view</button><button onClick={()=>run(()=>e.removeSession(r.id))}>Delete</button><button onClick={()=>download(new Blob([JSON.stringify({kind:'orrery-exploration',version:1,session:r},null,2)],{type:'application/json'}),'exploration.json')}>Export</button></div>)}
 <Field>Import session<input type="file" accept=".json" onChange={x=>{const f=x.target.files[0];if(f)run(async()=>{if(f.size>100000)throw new Error('Session exceeds 100 kB');const r=JSON.parse(await f.text());if(r.kind!=='orrery-exploration'||r.version!==1)throw new Error('Unsupported exploration session');e.loadSession(r.session);});x.target.value='';}}/></Field>{e.sessionJD&&<div><small>Recorded session epoch: {new Date((e.sessionJD-2440587.5)*DAY*1000).toISOString().slice(0,19)} UTC</small><button disabled={e.sessionJD>=2470172.5} onClick={()=>run(()=>{e.leave();sim.jump(new Date((e.sessionJD-2440587.5)*DAY*1000));go('universe');})}>Initialize Reality at session date</button></div>}<small>Sessions retain camera, layers, selection, scale and recorded epoch. Loading does not invent historical Sandbox states.</small></div></details>
 <details><summary>Compare stars and systems</summary><div className="stack"><Select label="Add comparison" value="" options={[['','Choose object'],...(solarSystem?[['solar-system','Solar System']]:[]),...STARS.filter(s=>['hyg-0','hyg-70666','hyg-32263','hyg-71456','hyg-87665'].includes(s.id)||s.apparentMagnitude!=null&&s.apparentMagnitude<2).map(s=>[s.id,s.name]),...SYSTEMS.map(s=>[s.id,s.name])]} commit={id=>e.update({compare:[...new Set([...e.compare,id])].slice(-5)})}/><ScienceTable columns={['Object','Mass M☉','Radius R☉','T K','L L☉','Planets','Max a AU']} rows={e.compare.map(id=>{const x=comparisonObject(id),h=x?.host??x;return [x?.name??id,metric(h?.mass,'',SOLAR_MASS),metric(h?.radius,'',SOLAR_RADIUS),metric(h?.temperature),metric(h?.luminosity,'',3.828e26),x?.planets?.length??'Unknown',x?.planets?metric(Math.max(...x.planets.map(p=>p.a??0)),'',AU):'Unknown'];})}/>{e.compare.map(comparisonObject).filter(x=>x?.planets).map(x=>{const hz=habitableZone(x.host.luminosity);return <div key={x.id}><h3>{x.name}</h3><small>Approximate HZ: {hz?formatDistance(hz.inner)+' – '+formatDistance(hz.outer):'Unknown'}</small><ScienceTable columns={['Planet','R⊕','Period d','a AU']} rows={x.planets.map(p=>[p.name,metric(p.radius,'',EARTH_RADIUS),metric(p.period,'',DAY),metric(p.a,'',AU)])}/></div>;})}<button onClick={()=>e.update({compare:[]})}>Clear</button><small>Lifetimes are unknown without evolutionary data.</small></div></details>
 <small>{STARS.length.toLocaleString()} stars · {SYSTEMS.length} systems. Retrieved {metadata.retrievedAt.slice(0,10)}. <a href="https://github.com/astronexus/HYG-Database/blob/main/hyg/README.md" target="_blank" rel="noreferrer">HYG CC BY-SA 4.0</a> · <a href="https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html" target="_blank" rel="noreferrer">NASA definitions</a>. Static catalog epoch.</small></div>;
}
