import {NumberField,Select,Toggle,Readouts,VectorField,fmt} from './Fields.jsx';
import {quaternionFromForward,dockingMetrics} from '../physics/dynamics.js';
export default function VehicleDynamics({body,bodies,edit,disabled}){
 const v=body.rocket??body.spacecraft,a=v.attitude,r=v.rcs,stage=body.rocket?.stages[body.rocket.stage];
 const change=fn=>edit(b=>fn(b.rocket??b.spacecraft,b));
 const enableRcs=()=>change((v,b)=>{v.rcs={fuel:20,thrust:20,torque:5,isp:220,leverArm:1,translation:[0,0,0],rotation:[0,0,0]};b.mass+=20;});
 let docking=null;try{const target=bodies.find(b=>b.id===v.docking?.targetId);if(target)docking=dockingMetrics(body,target);}catch{}
 return <details><summary>Attitude, engines & proximity operations</summary><div className="stack">
 <Select label="Attitude model" value={a?.mode??'orientation'} disabled={disabled} options={['orientation','rigid']} commit={mode=>change(v=>{v.attitude={mode,quaternion:a?.quaternion??quaternionFromForward(v.orientation),angularVelocity:[0,0,0],torque:[0,0,0],autopilot:true,maxTorque:body.rocket?1e6:50};})}/>
 {a?.mode==='rigid'&&<><Toggle label="Attitude PD guidance" disabled={disabled} value={a.autopilot} commit={x=>change(v=>v.attitude.autopilot=x)}/><VectorField label="Body torque (N m)" value={a.torque??[0,0,0]} unit="" disabled={disabled} commit={x=>change(v=>v.attitude.torque=x)}/><Readouts values={[['Quaternion (x y z w)',a.quaternion.map(x=>fmt(x,5)).join(' / ')],['Angular velocity · rad/s',(a.angularVelocity??[]).map(x=>fmt(x,5)).join(' / ')]]}/></>}
 {stage&&<><NumberField label="Sea-level thrust" value={stage.seaLevelThrust??stage.thrust} unit="N" disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].seaLevelThrust=Math.max(1,x))}/><NumberField label="Vacuum thrust" value={stage.vacuumThrust??stage.thrust} unit="N" disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].vacuumThrust=Math.max(1,x))}/><NumberField label="Sea-level Isp" value={stage.seaLevelIsp??stage.isp} unit="s" disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].seaLevelIsp=Math.max(1,x))}/><NumberField label="Vacuum Isp" value={stage.vacuumIsp??stage.isp} unit="s" disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].vacuumIsp=Math.max(1,x))}/><NumberField label="Gimbal range · degrees" value={v.gimbalRange??0} disabled={disabled} commit={x=>change(v=>v.gimbalRange=Math.max(0,Math.min(20,x)))}/>{[0,1].map((k)=><NumberField key={k} label={'Gimbal '+['yaw','pitch'][k]+' · degrees'} value={v.gimbal?.[k]??0} disabled={disabled} commit={x=>change(v=>{v.gimbal??=[0,0];v.gimbal[k]=x;})}/>)}
 <Select label="Descent guidance" value={v.landingAutopilot??'off'} disabled={disabled} options={['off','hover','descent']} commit={x=>change(v=>{v.landingAutopilot=x==='off'?null:x;if(x!=='off'){v.landingEnabled=true;v.landingSpeed=5;v.engineOn=true;v.autopilot=true;}})}/>
 <NumberField label="Maximum ignitions" value={stage.maxIgnitions??100} disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].maxIgnitions=Math.max(1,Math.min(10000,Math.round(x))))}/><Toggle label="Engine restart capable" value={stage.restartable!==false} disabled={disabled} commit={x=>edit(b=>b.rocket.stages[b.rocket.stage].restartable=x)}/><Toggle label="Structural warning limits enabled" value={!!v.limits} disabled={disabled} commit={x=>change(v=>{v.limits=x?{maxQ:80000,maxAcceleration:60,maxHeating:1e7}:null;})}/>{v.limits&&[['maxQ','Dynamic pressure limit · Pa',80000],['maxAcceleration','Acceleration limit · m/s²',60],['maxHeating','Heating proxy limit · W/m²',1e7]].map(([key,label,initial])=><NumberField key={key} label={label} value={v.limits?.[key]??initial} disabled={disabled} commit={x=>change(v=>{v.limits??={};v.limits[key]=Math.max(.01,x);})}/>) }
 <Readouts values={[['Ignitions used',stage.ignitionsUsed??0],['Actual Isp',fmt(v.actualIsp)+' s'],['Mass flow',fmt(v.massFlow)+' kg/s']]}/></>}
 {!r?<button disabled={disabled} onClick={enableRcs}>Install 20 kg RCS propellant</button>:<><Readouts values={[['RCS propellant',fmt(r.fuel)+' kg']]}/><VectorField label="RCS translation command (−1…1)" unit="" disabled={disabled} value={r.translation??[0,0,0]} commit={x=>change(v=>v.rcs.translation=x.map(y=>Math.max(-1,Math.min(1,y))))}/><VectorField label="RCS roll / pitch / yaw command" unit="" disabled={disabled} value={r.rotation??[0,0,0]} commit={x=>change(v=>v.rcs.rotation=x.map(y=>Math.max(-1,Math.min(1,y))))}/><button onClick={()=>change(v=>{v.rcs.translation=[0,0,0];v.rcs.rotation=[0,0,0];})}>Stop RCS commands</button></>}
 <Select label="Docking target" value={v.docking?.targetId??''} disabled={disabled} options={[['','None'],...bodies.filter(b=>b.id!==body.id&&(b.rocket||b.spacecraft)).map(b=>[b.id,b.name])]} commit={targetId=>change(v=>v.docking={targetId,armed:false})}/>
 <Toggle label="Arm close-range docking latch" value={v.docking?.armed} disabled={disabled||!v.docking?.targetId} commit={x=>change(v=>v.docking.armed=x)}/>
 {docking&&<Readouts values={Object.entries(docking).map(([k,x])=>[k,fmt(x,5)])}/>}
 <small>Docking requires port range ≤0.5 m, relative speed ≤0.1 m/s, lateral offset ≤0.25 m and opposed-axis error ≤0.05 rad. Kinematic latch; compound rigid-body rotation is omitted. Torque/RCS dynamics use capped physics steps.</small>
 {v.structuralWarnings?.map(x=><p className="warning" key={x}>{x}</p>)}
 </div></details>;
}
