import {useState,useMemo} from 'react';
import {useWhatIfStore} from '../store/useWhatIfStore.js';
import {useSimStore} from '../store/useSimStore.js';
import {QUICK_EXPERIMENTS,EXPERIMENT_PRESETS} from '../physics/experimentOps.js';
import {compareSnapshots} from '../physics/experimentAnalysis.js';
import {realityBodies} from '../physics/catalog.js';
import {AU,DAY,YEAR,G,norm,sub,add,scale,unit,julianDate,fromJulianDate} from '../physics/units.js';
import {NumberField,VectorField,Select,Toggle,Readouts,fmt} from './Fields.jsx';
import {Field} from './styles.js';
import {download,exportScenario} from '../persistence.js';
const factors=[.1,.25,.5,1,2,5,10,100,1000],date=jd=>fromJulianDate(jd).toISOString().slice(0,19);
function Result({result,selected}){
 if(!result)return <small>No simulated comparison yet. Long-term results require simulation.</small>;
 const c=result.comparison,row=c?.rows.find(r=>r.id===selected),max=result.maxSampledDeviation?.[selected];
 return <div className="stack"><h3>Baseline vs experiment</h3><Readouts values={[['Actually compared',fmt(Math.abs(result.advanced)/YEAR,6)+' yr'],['Requested horizon',fmt(Math.abs(result.requested)/YEAR,3)+' yr'],['Comparison',result.complete?'Reached requested horizon':result.aligned?'Partial horizon':'Epoch alignment incomplete'],['Matched samples',result.samples],['Captured start',date(result.startJD)+' UTC'],['Position difference',fmt(row?.positionDifference/1000,3)+' km'],['Velocity difference',fmt(row?.velocityDifference,3)+' m/s'],['Sampled maximum deviation',fmt(max/1000,3)+' km'],['Δ eccentricity',fmt(row?.eccentricityDifference,6)],['Baseline / experiment e',fmt(row?.baseline?.e,6)+' / '+fmt(row?.experiment?.e,6)],['Δ total energy',fmt(c?.energyDifference)+' J'],['Δ angular momentum',fmt(c?.angularMomentumDifference)+' kg·m²/s'],['Barycenter displacement',fmt(c?.barycenterDifference/1000)+' km'],['Baseline / experiment fuel',fmt(result.mission?.baselineFuel)+' / '+fmt(result.mission?.experimentFuel)+' kg'],['Predicted closest approach',fmt(result.closestApproach?.experiment?.distance/1000)+' km'],['Encounter relative speed',fmt(result.closestApproach?.experiment?.relativeSpeed/1000,3)+' km/s']]}/>{result.reason&&<p className="warning">! {result.reason}</p>}<small>{result.model} Energy difference between branches is intentional; it is not numerical drift.</small>
 <details><summary>All body differences</summary><div className="comparison-table"><table><thead><tr><th>Body</th><th>Status</th><th>Δ position · km</th><th>Δ velocity · m/s</th><th>e</th></tr></thead><tbody>{c?.rows.map(r=><tr key={r.id}><th>{r.name}</th><td>{r.status}</td><td>{fmt(r.positionDifference===null?null:r.positionDifference/1000)}</td><td>{fmt(r.velocityDifference)}</td><td>{fmt(r.experiment?.e,5)}</td></tr>)}</tbody></table></div></details>
 <details><summary>Simulated outcome timeline · {result.events?.length??0}</summary>{result.events?.map((e,i)=><div className="event" key={i}><small>{e.branch} · {date(e.jd)}</small><div>{e.kind}: {e.message}</div></div>)}<small>Escape/capture are sampled osculating-energy crossings, not proof of permanent capture or ejection. Event logs and paths are bounded.</small></details>
 <button onClick={()=>download(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),'orrery-experiment-report.json')}>Export simulation report · JSON</button>
 </div>;
}
export default function WhatIf({run}){
 const store=useWhatIfStore(),sim=useSimStore(),s=sim.scenario,b=s.bodies.find(b=>b.id===s.view.selected),original=store.baseline?.bodies.find(x=>x.id===b?.id),[name,setName]=useState('My experiment'),[preset,setPreset]=useState('noMoon'),[eventKind,setEventKind]=useState('mass'),[eventValue,setEventValue]=useState(.8),[delay,setDelay]=useState(DAY*30),[eventVector,setEventVector]=useState([1000,0,0]),[otherId,setOther]=useState('jupiter'),[sweepKind,setSweepKind]=useState('mass'),[start,setStart]=useState(.5),[end,setEnd]=useState(2),[sampleCount,setSamples]=useState(6),[departureStart,setDepartureStart]=useState('2031-01-01'),[departureEnd,setDepartureEnd]=useState('2031-12-31'),[transferDays,setTransferDays]=useState(259),[transferType,setTransferType]=useState('lambert'),[launchDate,setLaunchDate]=useState(fromJulianDate(s.jd).toISOString().slice(0,10)),[burnDuration,setBurnDuration]=useState(120),[parkingAltitude,setParkingAltitude]=useState(200000);
 const captured=useMemo(()=>store.before&&store.after?compareSnapshots(store.before,store.after):null,[store.before,store.after]);
 if(!store.active)return <div className="stack"><h2>What-If laboratory</h2><p>Branch the current state into a real N-body sandbox. The original scenario, pause state and edit history remain preserved.</p><button onClick={()=>run(store.begin)}>Enter WHAT-IF</button><button onClick={()=>run(store.recover)}>Recover last autosaved experiment</button><small>Apply commits the branch. Exit restores the original physical snapshot. Camera position stays under your control.</small></div>;
 const op=(kind,value,mode='set')=>store.operate({kind,bodyId:b.id,value,mode},b.name+' '+kind),configure=patch=>useWhatIfStore.setState({options:{...store.options,...patch}}),editVehicle=fn=>run(()=>sim.edit(d=>fn(d.bodies.find(x=>x.id===b.id).rocket)));
 const schedule=()=>run(()=>{if(!b&&eventKind!=='gravity')throw new Error('Select a body');let operation={kind:eventKind,bodyId:b?.id,value:eventValue,mode:'multiply'};
  if(['velocity','position','burn'].includes(eventKind))operation={kind:eventKind,bodyId:b.id,mode:'add',vector:eventVector,fuelAware:eventKind==='burn'&&!!b.rocket};
  if(eventKind==='create'){const source=structuredClone(b);source.id=crypto.randomUUID();source.name=b.name+' scheduled companion';source.position=add(b.position,eventVector);operation={kind:'create',body:source};}
  if(eventKind==='collision')operation={kind:eventKind,bodyId:b.id,otherId,speed:eventValue};
  if(['delete','ignite','cutoff','stage','fragment'].includes(eventKind))operation={kind:eventKind,bodyId:b.id,count:8};
  store.schedule(operation,s.jd+delay/DAY);
 });
 const shiftEpoch=()=>run(()=>sim.edit(d=>{
  const jd=julianDate(launchDate),oldBodies=new Map(d.bodies.map(b=>[b.id,structuredClone(b)])),newBodies=new Map(realityBodies(jd).map(b=>[b.id,b])),shift=jd-d.jd;
  for(const body of d.bodies){const next=newBodies.get(body.id);if(next&&!body.rocket&&!body.spacecraft){body.position=[...next.position];body.velocity=[...next.velocity];}}
  for(const body of d.bodies.filter(x=>x.rocket||x.spacecraft)){const old=oldBodies.get(body.parentId),next=newBodies.get(body.parentId);if(old&&next){body.position=add(next.position,sub(body.position,old.position));body.velocity=add(next.velocity,sub(body.velocity,old.velocity));}}
  d.jd=jd;for(const n of [...d.maneuvers,...d.experimentEvents])if(!n.executed)n.jd+=shift;
 }));
 return <div className="stack"><h2>What-If laboratory</h2><div className="whatif-status"><b>BASELINE</b><span>{store.baseline.name} · {date(store.baseline.jd)}</span><b>EXPERIMENT</b><span>{date(s.jd)} · N-body sandbox</span></div>
 <div className="grid"><button onClick={()=>run(()=>store.exit(true))}>Apply Changes</button><button onClick={()=>run(store.reset)}>Reset Experiment</button><button onClick={()=>run(()=>store.request())}>Compare</button><button onClick={()=>run(()=>store.exit(false))}>Exit Without Saving</button></div>
 <small>Apply keeps the current evolved branch and is undoable. Reset restores this branch's baseline. Exit restores the original scenario; the camera is preserved.</small>
 <details open><summary>Quick experiments</summary><div className="experiment-actions">{QUICK_EXPERIMENTS.map(([key,label])=><button key={key} onClick={()=>run(()=>store.quick(key))}>{label}</button>)}</div></details>
 <Select label="Experiment body" value={s.view.selected} options={s.bodies.filter(b=>!b.disrupted).map(b=>[b.id,b.name])} commit={selected=>sim.configureView({selected})}/>
 {b&&<details open><summary>Live parameters · {b.name}</summary><div className="stack">{!b.rocket&&<><NumberField label="Mass" value={b.mass} unit="kg" units={['kg','M⊕','M☉']} commit={v=>run(()=>op('mass',v))}/>{original?.mass>0&&<Field>Mass relative to baseline · {fmt(b.mass/original.mass,3)}×<input aria-label="Mass relative to baseline" type="range" min="-1" max="3" step=".01" value={Math.max(-1,Math.min(3,Math.log10(Math.max(.1,b.mass/original.mass))))} onChange={e=>run(()=>op('mass',original.mass*10**+e.target.value))}/></Field>}<div className="factor-row">{factors.map(x=><button key={x} onClick={()=>run(()=>op('mass',(original?.mass??b.mass)*x))}>{x}×</button>)}</div></>}
 <NumberField label="Physical radius" value={b.radius} unit="km" units={['m','km','R⊕','R☉']} commit={v=>run(()=>op('radius',v))}/><NumberField label="Density · changes mass at fixed radius" disabled={!!b.rocket} value={b.density??b.mass/(4/3*Math.PI*b.radius**3)} unit="kg/m³" commit={v=>run(()=>op('density',v))}/>
 <VectorField label="Position · inertial" value={b.position} unit="AU" commit={vector=>run(()=>store.operate({kind:'position',bodyId:b.id,mode:'set',vector}))}/><VectorField label="Velocity · inertial" value={b.velocity} unit="km/s" commit={vector=>run(()=>store.operate({kind:'velocity',bodyId:b.id,mode:'set',vector}))}/>
 <div className="factor-row">{[[.5,'−50%'],[.75,'−25%'],[1,'Current'],[1.25,'+25%'],[1.5,'+50%'],[2,'+100%'],[-1,'Reverse'],[0,'Zero']].map(([factor,label])=><button key={label} onClick={()=>run(()=>store.operate({kind:'velocity',bodyId:b.id,mode:'multiply',vector:[0,0,0],factor,relative:true}))}>{label}</button>)}</div><small>Velocity quick changes use the current primary-relative state. Inertial vector fields use the documented J2000 ecliptic basis.</small>
 <NumberField label="Spin period" value={b.spin.period} unit="d" units={['s','d']} commit={v=>run(()=>op('spin',v))}/><NumberField label="Axial tilt" value={b.axialTilt} unit="°" commit={v=>run(()=>op('tilt',v))}/><NumberField label="Temperature · visual/radiative parameter" value={b.temperature} unit="K" commit={v=>run(()=>op('temperature',v))}/><button onClick={()=>run(()=>store.operate({kind:'fragment',bodyId:b.id,count:8}))}>Fragment planet · conserved mass/momentum</button>
 </div></details>}
 <details open><summary>Prediction and comparison</summary><div className="stack"><Select label="Prediction horizon" value={store.options.duration} options={[[DAY,'1 day'],[7*DAY,'1 week'],[30*DAY,'1 month'],[YEAR,'1 year'],[10*YEAR,'10 years'],[100*YEAR,'100 years'],[store.options.duration,'Custom']]} commit={x=>configure({duration:Number(x)})}/><NumberField label="Custom horizon · negative integrates gravity backward" value={store.options.duration} unit="yr" units={['d','yr']} commit={x=>configure({duration:x})}/><NumberField label="Matched path samples" value={store.options.resolution} commit={x=>configure({resolution:Math.max(8,Math.min(256,Math.floor(x)))})}/><NumberField label="Worker budget" value={store.options.maxMs} unit="ms" commit={x=>configure({maxMs:Math.max(100,Math.min(12000,x))})}/>
 <Select label="Encounter target" value={s.view.targetId??'mars'} options={s.bodies.map(b=>[b.id,b.name])} commit={targetId=>sim.configureView({targetId})}/>
 <Toggle label="Automatic ghost comparison after edits · debounced" value={store.autoCompare} commit={autoCompare=>useWhatIfStore.setState({autoCompare})}/><Toggle label="Comparison overlay" value={store.overlay} commit={overlay=>useWhatIfStore.setState({overlay})}/><Toggle label="Baseline paths · thin dashed" value={store.baselinePaths} commit={baselinePaths=>useWhatIfStore.setState({baselinePaths})}/><Toggle label="Experiment paths · solid" value={store.experimentPaths} commit={experimentPaths=>useWhatIfStore.setState({experimentPaths})}/>
 <button onClick={()=>run(()=>store.request())}>{store.busy?'Restart comparison at current epoch':'Simulate comparison'}</button>{store.busy&&<button onClick={()=>{store.cancel();useWhatIfStore.setState({autoCompare:false});}}>Cancel analysis</button>}
 <small>Comparison uses cloned Sandbox engines. A Reality baseline is converted to Newtonian initial state for a controlled experiment. Both paths show the same reached epoch; long horizons may return partial results.</small>{s.settings.stepSeconds>3600&&<p className="warning">! Large timestep can under-resolve moons/local orbits; choose adaptive or a smaller step before trusting a prediction.</p>}
 <Result result={store.result} selected={s.view.selected}/>
 </div></details>
 <details><summary>Future changes</summary><div className="stack"><Select label="Event operation" value={eventKind} options={['mass','radius','gravity','velocity','position','delete','create','burn','ignite','cutoff','stage','collision','fragment']} commit={setEventKind}/><NumberField label="Delay from current simulation" value={delay} unit="d" units={['s','d','yr']} commit={x=>setDelay(Math.max(0,x))}/><NumberField label={eventKind==='collision'?'Collision relative speed · m/s':'Scalar multiplier'} value={eventValue} commit={setEventValue}/>{['velocity','position','burn','create'].includes(eventKind)&&<VectorField label={eventKind==='create'?'Companion offset':'Inertial change'} value={eventVector} unit={eventKind==='position'||eventKind==='create'?'km':'m/s'} commit={setEventVector}/>}<Select label="Other collision body" value={otherId} options={s.bodies.filter(x=>x.id!==b?.id).map(x=>[x.id,x.name])} commit={setOther}/><button onClick={schedule}>Schedule physical event</button>
 {s.experimentEvents.map(e=><div className="event" key={e.id}><small>{date(e.jd)} · {e.executed?(e.failed?'Rejected':'Executed'):'Pending'}</small><div>{e.operation.kind} · {e.operation.bodyId??'system'} {e.failed}</div>{!e.executed&&<button onClick={()=>run(()=>sim.edit(d=>d.experimentEvents=d.experimentEvents.filter(x=>x.id!==e.id)))}>Remove event</button>}</div>)}<small>Creation uses an absolute saved state vector at execution. Collision trigger places a real overlapping/approaching pair and enables merge; collisions then resolve in physics. Reverse time does not undo executed events.</small></div></details>
 <details><summary>Experimental scenarios and branching</summary><div className="stack"><Select label="Preset modification" value={preset} options={EXPERIMENT_PRESETS} commit={setPreset}/><button onClick={()=>run(()=>store.preset(preset))}>Apply experimental preset</button><small>These deliberately unrealistic changes are experiments, not stellar evolution models. Moving worlds into another planet's orbit can cause real overlaps.</small><Field>Branch name<input value={name} onChange={e=>setName(e.target.value)}/></Field><div className="grid"><button onClick={()=>run(()=>store.save(name))}>Save as Scenario</button><button onClick={()=>run(()=>store.fork(name))}>Branch from current experiment</button><button onClick={()=>run(()=>exportScenario(s))}>Export branch JSON</button><button onClick={()=>run(()=>store.planRandom(false))}>Surprise me · preview</button><button onClick={()=>run(()=>store.planRandom(true))}>Chaos mode · preview</button></div>
 {store.chaos.length>0&&<div className="experiment-plan"><strong>Planned bounded changes</strong>{store.chaos.map((o,i)=><p key={i}>{s.bodies.find(x=>x.id===o.bodyId)?.name}: {o.kind} ×{o.factor??o.value}</p>)}<button onClick={()=>run(store.executeRandom)}>Execute these changes</button><button onClick={()=>useWhatIfStore.setState({chaos:[]})}>Discard plan</button></div>}
 {store.branches.map((branch,i)=><small key={i}>{branch.name} · parent {branch.parentId.slice(0,8)} · {date(branch.jd)}</small>)}
 </div></details>
 {b?.rocket&&<details><summary>Rocket mission experiment</summary><div className="stack"><Field>Launch/initialization epoch · UTC<input type="date" min="1800-01-01" max="2050-12-31" value={launchDate} onChange={e=>setLaunchDate(e.target.value)}/></Field><button onClick={shiftEpoch}>Reinitialize planetary epoch; preserve vehicle relative state</button><small>This initializes approximate JPL vectors at the chosen date. It does not replay an already-flown launch.</small>
 <NumberField label="Initial circular orbit altitude" value={parkingAltitude} unit="km" units={['km','m']} commit={setParkingAltitude}/><button onClick={()=>run(()=>sim.edit(d=>{const vehicle=d.bodies.find(x=>x.id===b.id),parent=d.bodies.find(x=>x.id===vehicle.parentId);if(!parent||parkingAltitude<=vehicle.radius)throw new Error('Choose an altitude above the surface');vehicle.position=add(parent.position,[parent.radius+parkingAltitude,0,0]);vehicle.velocity=add(parent.velocity,[0,Math.sqrt(G*d.settings.gMultiplier*parent.mass/(parent.radius+parkingAltitude)),0]);vehicle.locked=false;vehicle.rocket.phase='coasting';vehicle.rocket.engineOn=false;}))}>Initialize actual circular parking orbit</button><small>Uses the current primary and SI circular velocity. This replaces the selected vehicle state; it does not simulate a launch.</small>
 <NumberField label="Payload mass" value={b.rocket.payloadMass} unit="kg" commit={x=>editVehicle(r=>r.payloadMass=x)}/>{b.rocket.stages.map((stage,i)=><div className="stack" key={i}><strong>{stage.name}</strong><NumberField label={'Stage '+(i+1)+' dry mass'} value={stage.dryMass} unit="kg" commit={x=>editVehicle(r=>r.stages[i].dryMass=x)}/><NumberField label={'Stage '+(i+1)+' fuel'} value={stage.fuel} unit="kg" commit={x=>editVehicle(r=>r.stages[i].fuel=x)}/><NumberField label={'Stage '+(i+1)+' thrust per engine'} value={stage.thrust} unit="N" commit={x=>editVehicle(r=>r.stages[i].thrust=x)}/></div>)}
 <NumberField label="Stage separation relative speed" value={b.rocket.separationSpeed??1} unit="m/s" commit={x=>editVehicle(r=>r.separationSpeed=x)}/><NumberField label="Powered interval" value={burnDuration} unit="s" commit={x=>setBurnDuration(Math.max(.01,x))}/><button onClick={()=>run(()=>sim.edit(d=>{d.experimentEvents.push({id:crypto.randomUUID(),jd:d.jd+delay/DAY,operation:{kind:'ignite',bodyId:b.id},executed:false},{id:crypto.randomUUID(),jd:d.jd+(delay+burnDuration)/DAY,operation:{kind:'cutoff',bodyId:b.id},executed:false});}))}>Schedule engine ignition + cutoff</button><small>Thrust and fuel consumption are integrated. Autopilot may cut off earlier; disable launch guidance for a controlled powered interval. Planned maneuver nodes remain fuel-aware impulses.</small>
 </div></details>}
 <details><summary>Bounded sensitivity analysis</summary><div className="stack"><Select label="Sweep parameter" value={sweepKind} options={[['mass','Selected mass multiplier'],['velocity','Selected relative velocity multiplier'],['gravity','G multiplier'],['departure','Earth–Mars departure date']]} commit={setSweepKind}/>{sweepKind==='departure'?<><Field>Start UTC<input type="date" value={departureStart} min="1800-01-01" max="2050-12-31" onChange={e=>setDepartureStart(e.target.value)}/></Field><Field>End UTC<input type="date" value={departureEnd} min="1800-01-01" max="2050-12-31" onChange={e=>setDepartureEnd(e.target.value)}/></Field><NumberField label="Lambert coast duration" value={transferDays*DAY} unit="d" commit={x=>setTransferDays(x/DAY)}/><Select label="Transfer estimate" value={transferType} options={[['lambert','Lambert · phased targeting'],['hohmann','Hohmann · circular coplanar estimate']]} commit={setTransferType}/></>:<><NumberField label="Multiplier from" value={start} commit={setStart}/><NumberField label="Multiplier to" value={end} commit={setEnd}/></>}<NumberField label="Coarse sample count · max 12" value={sampleCount} commit={x=>setSamples(Math.max(2,Math.min(12,Math.floor(x))))}/><button onClick={()=>run(()=>store.request('sensitivity',{kind:sweepKind,bodyId:b?.id,start:sweepKind==='departure'?julianDate(departureStart):start,end:sweepKind==='departure'?julianDate(departureEnd):end,samples:sampleCount,transferDays,transferType,maxMs:8000,duration:Math.abs(store.options.duration)}))}>Run bounded worker sweep</button>
 {store.sweep&&<><small>{store.sweep.model}</small><Readouts values={[['Completed samples',store.sweep.completedSamples+' / '+store.sweep.requestedSamples],['Lowest complete Δv',fmt(store.sweep.bestDV?.totalDV/1000)+' km/s'],['Best departure',store.sweep.bestDV?date(store.sweep.bestDV.value):'—'],['Closest complete encounter',fmt(store.sweep.bestEncounter?.closestApproach/1000)+' km']]}/>{store.sweep.rows.map((r,i)=><div className="event" key={i}><strong>{sweepKind==='departure'?date(r.value):r.value+'×'}</strong><small> {r.complete?'Complete':'Partial / rejected'} · {r.totalDV!=null?fmt(r.totalDV/1000)+' km/s':fmt(r.positionDifference/1000)+' km deviation'} {r.error??r.reason}</small></div>)}</>}
 </div></details>
 {(b?.spacecraft||b?.rocket)&&<details><summary>Maneuver timing experiments</summary><div className="stack">{s.maneuvers.filter(n=>n.bodyId===b.id&&!n.executed).map(n=><NumberField key={n.id} label={'Burn delay · '+n.id.slice(0,8)} value={(n.jd-s.jd)*DAY} unit="s" units={['s','d']} commit={seconds=>run(()=>sim.edit(d=>d.maneuvers.find(x=>x.id===n.id).jd=d.jd+Math.max(0,seconds)/DAY))}/>)}<button onClick={()=>sim.configureView({panel:'mission'})}>Open mission control / maneuver editor</button><small>Timing edits affect worker-executed maneuvers and cloned predictions. The experiment remains active across panels.</small></div></details>}
 <details><summary>Before / after captures</summary><div className="stack"><div className="grid"><button onClick={()=>run(()=>store.capture('before'))}>Capture Before</button><button onClick={()=>run(()=>store.capture('after'))}>Capture After</button></div>{captured&&<><small>{captured.aligned?'Same-epoch snapshots':'Different epochs: differences include time evolution; this is not a controlled same-epoch comparison.'}</small><Readouts values={[['Before UTC',date(captured.baselineJD)],['After UTC',date(captured.experimentJD)],['Energy difference',fmt(captured.energyDifference)+' J'],['Barycenter difference',fmt(captured.barycenterDifference/1000)+' km']]}/><button onClick={()=>download(new Blob([JSON.stringify(captured,null,2)],{type:'application/json'}),'orrery-before-after.json')}>Export before / after metrics</button></>}</div></details>
 {store.error&&<p role="alert" className="warning">! {store.error}</p>}{store.busy&&<small role="status">Computing cloned states in the analysis worker…</small>}
 </div>;
}
