import starsData from './data/stars.json';
import planetsData from './data/exoplanets.json';
import metadata from './data/metadata.json';
import {PC,LY,sphericalPosition,equatorialToEcliptic,galacticToEcliptic} from './coordinates.js';
import {SOLAR_MASS,SOLAR_RADIUS,EARTH_MASS,EARTH_RADIUS,AU,DAY} from '../physics/units.js';
export {metadata};
const positive=x=>typeof x==='number'&&Number.isFinite(x)&&x>0?x:null;
export const SYSTEMS=Object.entries(planetsData.reduce((groups,p)=>{(groups[p.hostname]??=[]).push(p);return groups;},{})).map(([name,planets])=>{
 const p=planets[0];return {id:'system:'+name,name:name==='Proxima Cen'?'Proxima Centauri':name,type:'system',position:p.sy_dist? sphericalPosition(p.ra,p.dec,p.sy_dist*PC):null,host:{mass:positive(p.st_mass)?p.st_mass*SOLAR_MASS:null,radius:positive(p.st_rad)?p.st_rad*SOLAR_RADIUS:null,temperature:positive(p.st_teff),luminosity:p.st_lum==null?null:10**p.st_lum*3.828e26,spectralType:p.st_spectype??null},planets:planets.map(p=>({id:'planet:'+p.pl_name,name:p.pl_name,type:'exoplanet',a:positive(p.pl_orbsmax)?p.pl_orbsmax*AU:null,period:positive(p.pl_orbper)?p.pl_orbper*DAY:null,radius:positive(p.pl_rade)?p.pl_rade*EARTH_RADIUS:null,mass:positive(p.pl_bmasse)?p.pl_bmasse*EARTH_MASS:null,massStatus:!positive(p.pl_bmasse)?'Unknown':p.pl_bmassprov==='M-R relationship'?'Estimated':p.pl_bmassprov==='Msini'?'Minimum mass':'Catalog value',massProvenance:p.pl_bmassprov,radiusStatus:!positive(p.pl_rade)?'Unknown':p.discoverymethod==='Radial Velocity'?'Composite / may be estimated':'Catalog composite',e:p.pl_orbeccen,temperature:p.pl_eqt,inclination:p.pl_orbincl,discoveryMethod:p.discoverymethod,discoveryYear:p.disc_year,radiusError:[p.pl_radeerr2,p.pl_radeerr1],massError:[p.pl_bmasseerr2,p.pl_bmasseerr1],source:'NASA Exoplanet Archive pscomppars'})),source:'NASA Exoplanet Archive pscomppars',status:'Catalog value'};
});
export const STARS=starsData.map(s=>{const system=SYSTEMS.find(x=>x.name===s.name||x.name==='Proxima Centauri'&&s.aliases.includes('Gl 551'));return {...s,type:'star',position:equatorialToEcliptic(s.positionEquatorialPc.map(x=>x*PC)),mass:s.id==='hyg-0'?SOLAR_MASS:system?.host.mass??null,radius:s.id==='hyg-0'?SOLAR_RADIUS:system?.host.radius??null,temperature:s.id==='hyg-0'?5772:system?.host.temperature??null,luminosity:system?.host.luminosity??(s.luminositySolar==null?null:s.luminositySolar*3.828e26),luminosityStatus:system?'NASA bolometric composite':s.id==='hyg-0'?'Solar reference':'HYG visual magnitude proxy',systemId:system?.id??null};});
export const GALAXIES=[
 {id:'milky-way',name:'Milky Way',type:'galaxy',position:galacticToEcliptic([26000*LY,0,0]),radius:50000*LY,distance:26000*LY,status:'Approximate',source:'NASA educational distance scale',description:'Schematic disk and spiral arms; no galactic N-body dynamics.'},
 {id:'sgr-a',name:'Sagittarius A*',type:'galactic center',position:galacticToEcliptic([26000*LY,0,0]),radius:1*LY,distance:26000*LY,status:'Approximate',source:'NASA educational distance scale',description:'Location marker only; not an active Solar System gravity source.'},
 {id:'andromeda',name:'Andromeda · M31',type:'galaxy',position:sphericalPosition(10.6847083,41.26875,2.5e6*LY),radius:130000*LY,distance:2.5e6*LY,status:'Approximate',source:'NASA/JPL PIA15416; J2000 center direction',description:'Illustrative galaxy orientation; approximate distance and disk extent.'},
 {id:'triangulum',name:'Triangulum · M33',type:'galaxy',position:sphericalPosition(23.462083,30.660194,3e6*LY),radius:30000*LY,distance:3e6*LY,status:'Approximate',source:'NASA Triangulum image article; schematic radius',description:'Illustrative orientation and disk size.'}
];
export const catalogOrigin=scenario=>SYSTEMS.find(s=>s.id===scenario.bodies.find(b=>b.type==='star')?.metadata?.catalogId)?.position??[0,0,0];
export const CATALOG=[...STARS,...SYSTEMS,...GALAXIES];
export function catalogObject(id){return CATALOG.find(x=>x.id===id)??SYSTEMS.flatMap(s=>s.planets.map(p=>({...p,systemId:s.id,position:s.position}))).find(x=>x.id===id);}
export function searchUniverse(query,bodies=[],limit=40){const q=query.toLocaleLowerCase().trim(),active=bodies.map(b=>({...b,id:'body:'+b.id,bodyId:b.id,context:'Active scenario'})),entries=[...active,...CATALOG,...SYSTEMS.flatMap(s=>s.planets.map(p=>({...p,position:s.position,systemId:s.id,context:s.name})))];return entries.filter(x=>([x.name,x.type,x.context,...(x.aliases??[])].join(' ')).toLocaleLowerCase().includes(q)).sort((a,b)=>{const rank=x=>x.name.toLocaleLowerCase()===q?0:x.name.toLocaleLowerCase().startsWith(q)?1:2;return rank(a)-rank(b)||a.name.localeCompare(b.name);}).slice(0,limit);}
export function catalogColor(s){const t=s.temperature;if(t!=null)return t<4000?'#d6a486':t>8000?'#b4c9e1':'#e7d3ae';const k=s.spectralType?.[0];return ['M','K'].includes(k)?'#d1aa91':['O','B','A'].includes(k)?'#b7cce4':'#ddd8ce';}
